### ISSUE TITLE
Unterscheidung nach Benutzergruppen

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/tricks#1]
Danke Thomas für deinen Einsatz! 
Wie darf ich verstehen, dass nicht nach Benutzergruppen unterschieden wird. Haben alle angemeldeten Benutzer Zugriff auf die Daten? Ist es Aufwändig, das ganze nur für eine bestimmte Benutzergruppe freizuschalten? Gerne auch manuell im Code?

Und zu guter letzt. Laut Jan steht auth_media in der Community auf dem Programm. Ist dein Trick hier ein "Alternative" dazu oder ist es sinniger später auf Auth_Media umzusteigen?

**Comment by staabm** [comment]
auf welchen "trick" hier im repository bezieht sich die Frage?

**Comment by skerbis** [comment]
@staabm Marco bezieht sich auf: 
https://github.com/FriendsOfREDAXO/tricks/blob/master/ycom_protected_files.md

@marcohanke 
Es lässt sich auch auf bestimmte Gruppen erweitern.
Am einfachsten gibst Du jeder Gruppe eine eigene Medienkategorie, die Du dann im Skript abfragst.  
Diese Lösung bietet einen einfachen per htaccess und ein wenig PHP realisierten Dateischutz. 

Was das Auth_Media können wird, kann ich nicht sagen. Ein Umstieg später ist bestimmt einfach möglich. Meine Lösung ist aus der Not entstanden, dass der Kunde sowas für eine Benutzergruppe brauchte.

**Comment by marcohanke** [comment]
@skerbis 
Ich habe das ganze etwas angepasst. Ob es "schön" ist, weiß ich nicht, es funktioniert auf jeden Fall, vielleicht willst du es ja mit einbinden:

Abfrage der Benutzergruppen die Zugang haben (bei mir sind es zwei)
`$group = rex_ycom_auth::getUser()->getValue('ycom_groups');;
if ($group == '2') {
	$permission = 'allowed';
} else if ($group == '3') {
	$permission = 'allowed';
} else {
	$permission = 'prohibited';
}
`

Und weiter unten dann in der Ausgabe nicht mehr nach `rex_ycom_auth::getUser();` gefragt, sondern `if ($permission == 'allowed')`

**Comment by skerbis** [comment]
@marcohanke Ich dachte Du möchtest bestimmten Gruppen Downloads anbieten, die aber jede eigene Kategorien haben. Gut, so erlaubst du natürlich nur bestimmten Gruppen den Download.

**Comment by marcohanke** [comment]
ich hab’ mir schon gedacht, dass du mich falsch verstanden hast.
Ich habe 3 Benutzergruppen Standard, Premium, Chef.
Standard ist kostenfrei und darf nichts downloaden.
Premium zahlt und darf downloaden.
Der Chef darf natürlich alles.

Das meint ich mit "das ganze nur für eine bestimmte Benutzergruppe freizuschalten“

**Comment by skerbis** [comment]
ok, dann ist dein Problem hiermit gelöst?

**Comment by marcohanke** [comment]
Für’s erste ja ;-)
