### ISSUE TITLE
Backend-Assets außerhalb von Media über den Media Manager laufen lassen:

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/tricks#100]
1. Im Media Manager einen neuen Mediatypen anlegen
2. Die gewünschten Effekte anlegen -> Wichtig: "Datei: Pfad anpassen" muss am Anfang stehen (Prio 1)
3. Beim Effekt "Datei: Pfad anpassen" im Feld Medienordner den Pfad eintragen (Bsp.: "assets/addons/mein_addon/imp_tmp/Dateien/")
4. Im Addon auf den Mediatypen zugreifen: `$body .= '<img src="index.php?rex_media_type=mein_mediatyp&rex_media_file=ein_bild.jpg" title="Bild" alt="Bild" />';`

via Michael Männer.

**Comment by skerbis** [comment]
Gratuliere zum 100. issue

**Comment by christophboecker** [comment]
Nicht dass ich Essig in den Wein kippen möchte - nur der Hinweis, dass das Verfahren seine Grenzen hat. Der Effekt ist nicht unbedingt mit anderen kombinierbar.

**Comment by skerbis** [comment]
@christophboecker kannst du das genauer erläutern? Gibt es dazu ein Issue bei REDAXO?

**Comment by christophboecker** [comment]
Das ist kein Issue, sondern "works as designed". Wenn ein Effekt zusätzliche Informationen aus dem Medienpool benötigt (dafür das rex_media-Objekt abrufen will), die Grafik dort aber nicht präsent ist (also NULL als Ergebnis des Abrufs), wird der Effekt halt nichts tun. Für die Im Standard mitgelieferten Effekte des MM ist das kein Problem, soweit mir bekannt. Effekte aus anderen Quellen (z.B. Focuspoint) funktionieren halt nur mit Bildern aus dem Medienpool. C´est la vie.

**Comment by skerbis** [comment]
@christophboecker ist das mit deiner aktuellen Version von focuspoint lauffähig.

**Comment by christophboecker** [comment]
Die aktuelle Version kann mit Bildern arbeiten, die obigen Effekt "Datei: Pfad anpassen" als ersten in der Liste haben. Aber: focuspoint kann für das Bild keine Koordinaten aus dem MP abrufen, logisch. Aber: wenn es keine anderen Angaben gibt, wird halt '50,50' = Bildmitte genommen. Alternativ kann in der Effektkonfiguration ein fester Wert hinterlegt werden (für MP-Bilder wäre es der Fallback-Wert falls das Bild einen leeren Eintrag hat). Und ... in der Url kann man auch einen  individuellen Wert mitgeben (...&xy=25,75). Der beim ersten Aufruf angegeben Wert bleibt aber solange wirksam, bis der Bildcache für die Datei gelöscht wurde.

Fazit: ja, es funktioniert. Irgendwie.
