### ISSUE TITLE
YFeed Media / BASE64 encoded Images:  Media Manager Effekte auf dieses Bild anwenden

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/tricks#102]
Frage zu YFeed Media: die Bilder liegen base64 codiert in der DB vor. Wie kann ich Media Manager Effekte auf dieses Bild anwenden. Hat da jemand Beispielcode?

echo '<a target="blank" href="'.$item['url'].'"><img alt="Bild zum Thema / Mehr Infos in Facebook" src="index.php?rex_media_type=yfeed&rex_media_file='.$item['id'].'.yfeed"></a>'; (edited)

**Comment by tbaddade** [comment]
Über MediaManager laufen lassen, da gibt es einen Effekt Yfeed.

**Comment by skerbis** [comment]
gehört zu yfeed
