### ISSUE TITLE
Notizen: Backend Customizing

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/tricks#104]
**Seite eines AddOns austauschen:** 

```php
rex_extension::register('PAGES_PREPARED',function($ep) {
  if (rex_be_controller::getCurrentPage() == 'structure') {
    $Page = rex_be_controller::getCurrentPageObject();
    $Page->setPath($this->getPath('pages/index.php'));
  }
});
```

**Addonseiten ausblenden**

```php

if (rex::isBackend()  and rex_backend_login::hasSession()) {
$page = rex_be_controller::getPageObject('system');
$page->setHidden(true);
$page->setPath('...');

$page = rex_be_controller::getPageObject('packages');
$page->setHidden(true);
$page->setPath('...');

}
```

**Medienpool Sortierung ändern**

```php
    // Sortierung Medienpool aufsteigend
    if (rex::isBackend() && rex::getUser()) {
        rex_extension::register('MEDIA_LIST_QUERY', function (rex_extension_point $ep) {
            $subject = $ep->getSubject();
            $subject = str_replace("f.updatedate", "f.filename, f.updatedate", $subject);
            $subject = str_replace("desc", "asc", $subject);
            return $subject;
        });
```

**Comment by skerbis** [comment]
@alexplusde es geht hier darum, dies aus einem anderen AddOn heraus zu machen. Ist dies auch über die package.yml so möglich?
Ich möchte z.B. einen eingeschränkten Administrator so erzeugen.

**Comment by alexplusde** [comment]
Ich meinte, das hatte ich per Zufall rausgefunden, wenn ich eine subpage angebe, die bereits existiert und ich damit überschreibe. allerdings war das nicht von mir beabsichtigt, deswegen habe ich auch kein funktionierendes Beispiel parat.

**Comment by skerbis** [comment]
Stimmt. Das könnte so gehen. Ist aber ggf. davon abhängig in welcher Reihenfolge die AddOns geladen werden - oder? @alexplusde

**Comment by skerbis** [comment]
Ja, es geht viel viel mehr. Die package.yml ist ja individuell nutzbar, die nötigen Abfragen muss man aber selbst realisieren. Kommen also nicht vom Core

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/tricks/blob/master/_docs/backend/backend_snippets.md#mediasort
