### ISSUE TITLE
package.yml Übersicht

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/tricks#105]
In dieser Datei können so viele Parameter auf unterschiedliche Art und Weise geschrieben werden, dass es sich lohnen würde, diese Parameter immer aufzulisten und kommentieren. Einschließlich Addon Parameter wie beim YForm.

In diesem issue können wir die Sachen schon mal sammeln...

**Comment by skerbis** [comment]
https://redaxo.org/doku/master/addon-package
Was fehlt da?

**Comment by skerbis** [comment]
Da keine Antwort, erstmal close

**Comment by alexplusde** [comment]
Sorry, Frage ging mir durch die Lappen

https://friendsofredaxo.github.io/tricks/
> YForm > in eigenes Add-On einbinden

Da bspw. Parameter "subPage"
