### ISSUE TITLE
Daten aus Modul im Template verfügbar machen, zB um Title o.ä. zu steuern

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/tricks#107]
Via *rex::getProperty('bla')* kann man beim rendern schon im Template Variablen verfügbar machen, die erst im Modul generiert werden. 

Ablauflogik im Template ist dann beim Beispiel von header-Tags wie folgt: 
Erst den Artikel abrufen `$this->getArticle();`.
Dann im fraglichen Modul mit `rex::setProperty('bla',"blubb")` die Tags-Information hinterlegen. Danach erst im Template die ganze Ausgabe zusammenschrauben und dabei die Tags mit `rex::getProperty('bla')` abrufen:

Das kann im Template dann etwa so aussehen:
```
$seo = new rex_yrewrite_seo();
if (rex::getProperty('head_title') != "") {
echo 	"<title>".rex::getProperty('head_title')."</title>";
}
else {
echo $seo->getTitleTag().PHP_EOL;
}

```

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/tricks/issues/89

**Comment by skerbis** [comment]
duplikat von

**Comment by cukabeka** [comment]
Einspruch - im Gegensatz zu #89 gibt es hier ein konkretes Beispiel als Code. Die Frage taucht immer wieder auf: Wie kann ich im Template Daten verfügbar machen, die erst später aus der DB geholt werden. Das hier beschreibt die einzige mir bekannte Lösung und ist IMHO ein echter Trick, wie ein REX-Kernproblem gelöst werden kann, ohne zu viele DB-Abfragen schon im Template zu machen.

**Comment by skerbis** [comment]
Wird als Beispiel in die Docs aufgenommen

**Comment by skerbis** [comment]
Danke @cukabeka 
https://github.com/redaxo/docs/blob/master/eigenschaften.md#beispiele
