### ISSUE TITLE
YForm: Sortierung des Table Manager erweitern

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/tricks#108]
Im Table Manager lässt sich _ein_ DB-Feld für die Sortierung der Backendausgabe festlegen. 
Manchmal ist eine komplexere Sortierung sinnvoll: `ORDER BY column1, column2`

Folgendes Snippet kann im Projekt Addon oder Theme Addon platziert werden und ermöglicht es die Sortierung zu erweitern:

```
if(rex::isBackend() && rex_addon::get('yform')->isAvailable() && rex_plugin::get('yform', 'manager')->isAvailable() &&
   rex_be_controller::getCurrentPage() == 'yform/manager/data_edit' && rex_request('table_name') == '<TABLE_NAME>') {
	rex_extension::register('YFORM_DATA_LIST_SQL', function(rex_extension_point $ep){
		$sortField = $ep->getParam('table')->getSortFieldName();
		$sortOrder = $ep->getParam('table')->getSortOrderName();
		$fields = $ep->getParam('table')->getFields();

		// dont prevent sorting of other columns
		if(rex_request("sort") != "" && rex_request("sort") != $sortField) {
			return;
		}

		$subject = preg_replace(
			"@ORDER BY `id` ASC$@i", "ORDER BY <SOMETHING ELSE>",
			$ep->getSubject()
		);

		$ep->setSubject($subject);
	}, rex_extension::LATE);
}
```
`<TABLE_NAME>` und `<SOMETHING ELSE>` austauschen und  darauf achten das in der Tabellen Konfiguration die Standardsortierung auf `id` und die Richtung auf  `aufsteigend` steht.

**Comment by alexplusde** [comment]
Das müsste auch für WHERE-Bedingungen gelten. Damit könnte man bspw. Nutzer vorweg Datensätze filtern lassen und bspw. nur eigene Datensätze oder Datensätze einer bestimmten YRewrite-Domain anzeigen lassen.

**Comment by christophboecker** [comment]
Ich mache es ähnlich. Grundsätzlich funktioniert das. Sogar Listenfelder kann man umbauen. Beispiel: 'name' und 'vorname' sind zwei Felder im Formular (und damit in der Liste), blende ich 'vorname' aus der Liste aus und ersetze 'name' durch 'CONCAT(name,", ",vorname) as name'. Die Where-Klauseln kann man auch beeinflussen. Mit festen Vorgabewerten alles kein Problem. Benutzereingaben reinzubekommen, könnte kniffelig werden.

**Comment by godsdog** [comment]
Noch ein Hinweis dazu: Das geht nur, solange keine andere Spalte zum Sortieren ausgewählt wird. Will man eine andere Spalte zum sortieren auswählen wirft der EP nicht das passende Query aus.

**Comment by skerbis** [comment]
danke @isospin
https://github.com/FriendsOfREDAXO/tricks/blob/master/_docs/addons/yform/snippets.md
