### ISSUE TITLE
Code: Warum nur Einrückung statt ```?

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/tricks#11]
In der [Vorlage](https://github.com/FriendsOfREDAXO/tricks/blob/master/_vorlage.md) steht:

> Code wird einfach nur via Tabs eingerückt
Nicht die ``` verwenden

Warum ist das so? Werden die Inhalte irgendwie geparst und aufbereitet, und der Parser benötigt diese Form von Code-Auszeichnung?

Mag mal jemand erklären, in welcher Form die Inhalte der Tricks überhaupt verarbeitet werden?

**Comment by skerbis** [comment]
@tbaddade wollte das so, um es ggf. in die neue Website einzubinden.

**Comment by tbaddade** [comment]
> Warum ist das so?

Ausgangsbasis war mal das normale Markdown ohne irgendwelche zusätzlichen Abhängigkeiten und somit zusätzlichen Parser. Wenn ich mich recht erinnere, stammt die Vorlage aus redaxo/docs

**Comment by polarpixel** [comment]
> Wenn ich mich recht erinnere, stammt die Vorlage aus redaxo/docs

Richtig. Wenn wir also sagen, wir werden die Tricks nie in die Website einbinden, könnte diese Einschränkung ja vermutlich weg.

**Comment by skerbis** [comment]
Ich würde es als "Schade" empfinden, da die Tricks auch eine Ergänzung zur Doku darstellen könnten. Tiefergehend halt mit Anwendungsbeispielen.

**Comment by tbaddade** [comment]
Es geht ja um die Parser (da gibt es ja einige) und das wir alle eine Code-Basis nutzen. Da der Core bereits **parsedown + parsedown-etxra** mit bringt, können wir auch gern ``` und alles was parsedown-extra noch so mitbringt verwenden.

**Comment by schuer** [comment]
Für die Lesbarkeit direkt auf Github wäre die Nutzung von ausgezeichnetem Code mit Syntaxhighlighting schöner als nur die Einrückung, die wir gerade haben. Aber es ist sicherlich sinnvoll, einheitlich mit den Core-Docs zu bleiben.

Bleiben also zwei Möglichkeiten?

* core/docs und Tricks auf richtige Codeauszeichnung umstellen
* Alles so lassen, wie es jetzt ist

**Comment by skerbis** [comment]
Noch ist nicht viel passiert, daher lässt sich noch alles ändern, wenns denn sein soll. Ich denke, das Doku-Team sollte entscheiden.

**Comment by gharlan** [comment]
Ich bin auf jeden Fall für ``` mit Angabe der Sprache.
So kann man auf redaxo.org dann auch mal Syntaxt-Highlighting für verschiedene Sprachen anbieten etc.

**Comment by schuer** [comment]
Betrifft das auch die anderen Dokus, die in der Zwischenzeit entstanden sind? Etwa yform und die anderen, die die Hilfe mittels Doku-Plugin anzeigen?

**Comment by tbaddade** [comment]
> Betrifft das auch die anderen Dokus, die in der Zwischenzeit entstanden sind?

YForm-Docs verwendet die Core Methode `rex_markdown()` und wäre somit alles gut.
https://github.com/redaxo/redaxo/blob/master/redaxo/src/core/lib/util/markdown.php#L10

**Comment by alexplusde** [comment]
@aeberhard dein Doku-Plugin verwendet demzufolge auch die Core-Methode?

**Comment by skerbis** [comment]
Kurz ich darf jetzt  ```php verwenden?

**Comment by aeberhard** [comment]
@alexplusde ja wenn vorhanden wird die Core-Methode verwendet
https://github.com/FriendsOfREDAXO/demo_addon/pull/17/files#diff-da18c40a7634ed35a8baa57a83e463a8R126

ping @schuer fürs Demo-Addon ist noch ein PR offen :)

**Comment by schuer** [comment]
Okay, dann ist das doch jetzt durch, und wir können alles auf die Backtick-Notation umstellen, was?
Sonst gerne wieder öffnen.
