### ISSUE TITLE
Tricks löschen?

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/tricks#111]
Darf auch was aus den Tricks geöscht werden? Der Teil zu Focuspoint ist mittlerweile in der Focuspoint-internen Doku enthalten. Ich würde ihn hier gerne rauswerfen, um nicht zwei doppelt aktuell halten zu müssen.

**Comment by schuer** [comment]
Meine Meinung: Ja, ruhig löschen und in den Tricks an der Stelle einen Hinweis auf die Doku anbringen.

**Comment by skerbis** [comment]
Wenn es in der Doku enthalten ist, kann es aus meiner Sicht ganz raus. Ohne Verweise etc.

**Comment by schuer** [comment]
(Achso, ich hatte es falsch verstanden: Der ganze Trick/Artikel soll weg, nicht nur Teil davon. Dann bin ich voll bei skerbis: Keine Verweise notwendig, einfach alles löschen.)

**Comment by skerbis** [comment]
@christophboecker du darfst löschen
