### ISSUE TITLE
Änderung im Sked-Modul mit Kalenderausgabe

### ISSUE THREAD

**Issue by javanita** [FriendsOfREDAXO/tricks#113]
das JS hat einen Fehler bei der lightgallery verursacht

Lösung: das JS direkt in die Modulausgabe schreiben in den script-Teil

**Comment by skerbis** [comment]
Also eher, 
Hinweis: Bei Verwendung der Lightgallery könnte es zu einem Konflikt kommen. Hier sollte das JS direkt im Modul notiert werden. 

So in etwa?

**Comment by skerbis** [comment]
> vieleicht wäre aber auch eine Möglichkeit, das js am Ende der Seite zu laden
Kannst du es bitte testen. Finde ich persönlich smarter

**Comment by javanita** [comment]
hab ich gemacht, funzt

**Comment by skerbis** [comment]
erledigt
