### ISSUE TITLE
Schriftgröße und Zeilenabstand

### ISSUE THREAD

**Issue by Koala** [FriendsOfREDAXO/tricks#118]
Ich empfinde die Schriftgröße für den normalen Text mit 19px viel zu riesig. Die Größe wie in der Doku sollte doch völlig ausreichen.
Ebenso ist der Zeilenabstand sehr groß (was jetzt auch etwas täuschen kann, wegen der großen Schrift).

https://github.com/FriendsOfREDAXO/tricks/blob/d3b6c60235826280ca9823d58f0c070247c7718d/_sass/_content.scss#L8

**Comment by schuer** [comment]
Habe mal zum Test die Schriftgrößen etwas reduziert. Besser, @Koala?
Und was meinen die anderen?

**Comment by schuer** [comment]
Nochmal kleine Anpassungen vorgenommen, schau mal: https://friendsofredaxo.github.io/tricks/module/artikel_einbinden
Besser?

**Comment by Koala** [comment]
Deutlich besser für meine Augen :-)

**Comment by Koala** [comment]
![screenshot_20181230_174813](https://user-images.githubusercontent.com/330686/50549323-1ecfc180-0c5b-11e9-9e0d-2ad4efbceae9.png)

**Comment by schuer** [comment]
Top, danke für dein Feedback!
