### ISSUE TITLE
Navigationen erstellen mittels rex_navigation::factory() ->Doku

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/tricks#12]
Ist eher was für die Redaxo-Doku - oder?
https://github.com/FriendsOfREDAXO/tricks/blob/master/templates_navigation-factory.md

**Comment by alexplusde** [comment]
+1

**Comment by skerbis** [comment]
denke, man kann es schließen
https://github.com/redaxo/docs/blob/master/navigationen.md
