### ISSUE TITLE
Sked: Aktueller Tag wird nicht angezeigt

### ISSUE THREAD

**Issue by EdwinMosesPray** [FriendsOfREDAXO/tricks#120]
Hallo
Bei mir wird der Termin am aktuellen Tag nicht angezeigt, wenn ich 'Vierteljahr' bzw. 'Halbes-Jahr' wähle. Bei der Auswahl 'Ganzer Zeitraum' wird natürlich alles angezeigt.
Danke für die Hilfe,
Frank

**Comment by skerbis** [comment]
Hast du meine Antwort im Forum gelesen? Hat das geholfen?

**Comment by EdwinMosesPray** [comment]
Leider nicht, Thomas

**Comment by EdwinMosesPray** [comment]
Gerade mal getestet:
Gebe ich Anfangsdatum 7.1. und Enddatum 8.1. - 00:01 an, wird der Termin angezeigt

**Comment by skerbis** [comment]
$start = date("Y-m-d 00:00:00"); 
sollte helfen.

**Comment by skerbis** [comment]
Welches Modul verwendest du? Das aus der Doku?

**Comment by EdwinMosesPray** [comment]
Hey Thomas

JETZT funktionirt es  *freu
Den _$today = date("Y-m-d");_ Eintrag habe ich auch noch drin gelassen, für alle Fälle. Es ist sogar von Vorteil, dass der Termin erst um Mitternacht verschwindet, auch wenn er schon Stunden vorher vorbei ist. So sieht man, dass man ggf. einen Termin verpasst hat. Ich -persönlich- wäre sogar dafür, den Termin noch 1 Tag länger stehen zu lassen. 

Ja, der Code für das Eingabe- und Ausgabemodul ist aus der Doku.

Vielen lieben Dank,
Frank

**Comment by skerbis** [comment]
Ok. Beim nächsten mal bitte ein issue bei sked und nicht in den tricks 😎
