### ISSUE TITLE
Von Interesse? Durchsuchbare Icon-Übersicht?

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/tricks#123]
Ich wollte mal endlich eine durchsuchbare Liste aller Icons haben, die in der "styles.css" definiert sind. Herausgekommen ist eine Helferseite im Projekt-Addon. Icon-Kategorie(.fa, .rex-icon, .glyphicon) ist auswählbar; Freitextsuche in den Klassennamen. Doppelklick auf den Klassennamen kopiert den jeweiligen i-Tag ins Clipboard.

Wäre das von Interesse für die Tricks? Wenn ja: in welche Rubrik - Backend, Diverses, Snippets?  

<img width="843" alt="grafik" src="https://user-images.githubusercontent.com/10065904/51799583-01265580-2223-11e9-9746-b32004ea5edf.png">

**Comment by skerbis** [comment]
Vielleicht was für das cheatsheet addon? Sonst würde ich sagen,Backend

**Comment by skerbis** [comment]
Finde es super und sehr hilfreich.
