### ISSUE TITLE
Password ändern erweitern, sodass aktuelles Passwort mit abgefragt wird

### ISSUE THREAD

**Issue by rotzek** [FriendsOfREDAXO/tricks#128]
Hab ich grad aus slack entnommen, vielleicht noch generalisieren und php-Variante hinzufügen?

objparams|Error-occured|Es sind Fehler in Ihrer Eingabe vorhanden
objparams|form_showformafterupdate|1
objparams|hide_field_warning_messages|false
objparams|hide_top_warning_messages|true
objparams|submit_btn_show|false

html|||<div data-case-grid="6-6">
html|||<div class="case-grid-item">

html|||<h3>Passwort ändern <span class="form-required"><span class="form-required-sign">*</span> {{ form.required.fields }}</span></h3>

hidden|new_password_required|0

password|old_password|{{ old_password }}:*||no_db|#placeholder:_
validate|empty|old_password|{{ error_enter_old_password }}
validate|ycom_auth_password|old_password|{{ error_not_old_password }}

ycom_auth_password|password|{{ new_password }}:*|{"length":{"min":8},"letter":{"min":1},"lowercase":{"min":1},"uppercase":{"min":1}}|{{ error_password_policy }}|#placeholder:_
validate|empty|password|{{ error_enter_password }}
validate|compare|password|password_2|!=|{{ error_enter_password_same }}

password|password_2|{{ new_password_repeat }}:*||no_db|#placeholder:_

html|||</div>
html|||</div>

html|||<div data-case-grid="6-6">
html|||<div class="case-grid-item align-right">
html|||<button class="btn btn-primary" type="submit">{{ send }}</button>
html|||</div>
html|||</div>

action|showtext|<div class="alert alert-success">{{ password_changed }}</div>|||1
action|ycom_auth_db

**Comment by alexplusde** [comment]
https://github.com/yakamara/redaxo_yform_docs/issues/122
