### ISSUE TITLE
rex:ready event

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/tricks#13]
R5 nutzt Pjax, deshalb reich der klassische jQuery `document:ready` manchmal nicht. Die Alternative dazu ist der `rex:ready` Event - der greift immer wenn neuer Content bereit steht, egal ob über Pjax oder nicht.

```
$(document).on('rex:ready', function (event, container) {
    container.find('.selectpicker').selectpicker();
});
```
das findet sich so zum beispiel im be_style-Plugin. `container` ist immer der Container, der ausgetauscht wurde. Initial bei document:ready ist es der `<body>`.

**Comment by alexplusde** [comment]
Ist das nicht was für die offizielle Doku?

**Comment by skerbis** [comment]
@alexplusde dafür ist das label da

**Comment by skerbis** [comment]
https://github.com/redaxo/docs/blob/master/addon-assets.md#rexready
Danke @IngoWinter
