### ISSUE TITLE
UTFMB4 :: Vor dem Update auf YForm 3.0 auf zu lange Strings prüfen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/tricks#135]
Strings konnten vorher max. 255 Zeichen besitzen. Mit dem Update ist dies auf 191 begrenzt. Daher sollte vorher geprüft werden, ob zu lange Strings enthalten sind.

- Das SQL könnte noch optimiert werden.
- Es wird nur auf text-values geprüft

```
$sql = rex_sql::factory();
$fields = $sql->getArray('SELECT * FROM '.rex::getTable('yform_field').' WHERE type_name = "text"');
foreach ($fields as $field) {
    $s = rex_sql::factory();
    $items = $s->getArray('SELECT * FROM '.$field['table_name'].' WHERE length('.$field['name'].') > 191');
    if (count($items)) {
        dump($field['name'], $items);
    }
}
```

**Comment by skerbis** [comment]
Sollte das nicht in die Update-Info von YForm? Ich denke das Issue hier geht unter

**Comment by alexplusde** [comment]
Grund dafür ist die Umstellung auf utf8mb4 - was streng genommen das echte utf8 ist. Und ich meinte, das wird im Changelog genannt.

**Comment by staabm** [comment]
Muss man das überhaupt „erwähnen“/manuell prüfen oder kann man das in der update.php prüfen und ggf. Abbrechen?

**Comment by skerbis** [comment]
@staabm @tbaddade - Das wäre doch was für ein **precheck** im Installationsablauf. Also man zwingt den wenigen erst den check durchzuführen und warnt ihn vor Komplikationen. Erst nach Bestätigung würde installiert werden. - Macht das für Euch Sinn?

**Comment by alexplusde** [comment]
Bisher scheint es hier nicht zu nennenswerten Vorkommnissen gekommen zu sein...

**Comment by alexplusde** [comment]
Ist dies hinfällig mit der von der Kompatibilität späterer MySQL-Versionen mit utf8mb4? @gharlan @dergel @staabm

**Comment by alexplusde** [comment]
@gharlan hat mir schon nebenan geantwortet. 

@dergel könntest du das vlt. einfach in die Updatehinweise vom Installer packen, denn das gehört für mich eher da hin als hier.

**Comment by tbaddade** [comment]
Ich schließe hier, da es zu Yform gehört und kein Trick sein sollte.
