### ISSUE TITLE
Redaxo Klassen ausserhalb Redaxo Kontext nutzen

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/tricks#136]
```
$REX['REDAXO'] = false;
$REX['HTDOCS_PATH'] = '../../../../';
$REX['BACKEND_FOLDER'] = 'redaxo';
$REX['LOAD_PAGE'] = false;

require $REX['HTDOCS_PATH'].$REX['BACKEND_FOLDER'].'/src/core/boot.php';
```

**Comment by skerbis** [comment]
Danke @IngoWinter

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/tricks/blob/master/_docs/snippets/require_redaxo.md

**Comment by alexplusde** [comment]
Warum will man das und möchte nicht stattdessen die rex_api oder dergleichen dafür bemühen?

**Comment by skerbis** [comment]
Weil man ggf. einen direkten Zugriff auf die Classes benötigt oder vielleicht z.B eine fertig gerenderte Seite ausgeben möchte in der anderen Applikation
