### ISSUE TITLE
Nicht öffentliche addons via installer

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/tricks#139]
Zitat slack

Problemstellung
> Mal ne Frage an die Redaxo-Entwickler: Ist es prinzipiell möglich (klar, da muss noch was erweitert/umgeschrieben werden), für den Installer einen eigenem Server zu nutzen? Ich frage, weil ich in so gut wie jedem Projekt mehrere eigene Addons verwende, die mir die Arbeit noch weiter erleichtern, die aber für die Allgemeinheit eher sinnlos sind. Ein Update dieser Addons wäre auf die Art natürlich sehr viel einfacher... momentan läuft das alles über Subversion...

Antwort 

> eine sache noch: wenn du einen API-key angibst, kannst du über den installer addons laden, die du selbst veröffentlicht hast, die aber offline sind, also nicht öffentlich verfügbar sind.
zu bedenken ist dabei allerdings, dass dieser API-key auch schreibrechte hat, dass also alle administratoren deiner redaxo-installation damit theoretisch zugriff auf deine addons haben und diese verändern könnten.

**Comment by skerbis** [comment]
danke @staabm  
https://github.com/redaxo/docs/blob/master/addon-veroeffentlichung.md#testing
