### ISSUE TITLE
Assets im Backend nur bei eigenem Addon/Unterseiten einbinden

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/tricks#140]
Aber wohin mit dem Snippet ? @skerbis bei "Backend Snippets" dazupacken?

```
    if (rex_be_controller::getCurrentPagePart(1) == 'meinaddon') {
        rex_view::addCssFile($this->getAssetsUrl('css/meincss.css'));
        rex_view::addJsFile($this->getAssetsUrl('js/meinjs.js'));
    }
```

Evtl. noch Beispiel für Unterseiten des Addons mit getCurrentPagePart(2)

**Comment by skerbis** [comment]
Hi 👋 schau mal hier: https://redaxo.org/doku/master/addon-assets

**Comment by aeberhard** [comment]
Ah da steht's ja bereits :)
Dann kann hier ja eigentlich zu ...
