### ISSUE TITLE
YForm: Reihenfolge der Listenansicht ändern

### ISSUE THREAD

**Issue by pschuchmann** [FriendsOfREDAXO/tricks#142]
Hey,

da ich das Problem gerade hatte und im Slack ein paar Anregungen bekommen habe, hier ein wenig Code um in YForm Tabellen die Sortierung der Felder in der Listenansicht zu ändern (Datensatz editieren bleibt unabhängig).

```
rex_extension::register('YFORM_DATA_LIST_SQL', function ($ep) {
  $params  = $ep->getParams(); // EP Params holen
  $subject = $ep->getSubject(); // EP Subject (SQL) holen
  // dump($subject); //SQL der rex_list ausgeben lassen

  if ($params['table'] == rex::getTable('my_table')) {

    $sql = 'my_sql_query'; // SQL neu sortieren

    $subject = $ep->setSubject($sql); // neue Liste setzen

  }

  return $subject; // neue Liste zurück geben

});
```

@christophboecker hatte mich auf den EP gestoßen, vielleicht hilft es ja auch Anderen!

**Comment by skerbis** [comment]
Danke @pschuchmann 
https://github.com/FriendsOfREDAXO/tricks/blob/master/_docs/addons/yform/snippets.md
