### ISSUE TITLE
YForm: Spalte ausblenden

### ISSUE THREAD

**Issue by netzproductions** [FriendsOfREDAXO/tricks#144]
Beim Einsatz einer YForm-Tabelle im eigenen AddOn können beliebige Spalten über den Einsatz des folgenden Extension points ausgeblendet werden (hier als Beispiel die Spalte ID):

```

if (rex::isBackend())
{
	rex_extension::register("YFORM_DATA_LIST", function( $ep ) {  

	if ($ep->getParam("table")->getTableName()=="gewuenschte_tabelle"){
		$list = $ep->getSubject();

		$list->removeColumn("id");
	});
});

``` 

Das Snippet kommt am besten in die boot.php des project-AddOns.

**Comment by alexplusde** [comment]
Danke für die Code-Snippets - am besten bei mehrzeiligem Code 3 Backticks nehmen (siehe editierten Beitrag)

**Comment by skerbis** [comment]
Danke @netzproductions https://github.com/FriendsOfREDAXO/tricks/blob/master/_docs/addons/yform/snippets.md
