### ISSUE TITLE
YForm Snippets zur Doku übertragen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/tricks#146]
@alexplusde Ich habe die YForm-Snippets hier gesammelt: 

https://github.com/FriendsOfREDAXO/tricks/blob/master/_docs/addons/yform/snippets.md

Ich denke, da sie relativ allgemein sind, wären sie was für die Doku.
Was denkst Du?

**Comment by alexplusde** [comment]
Beziehen sich alle auf den Table Manager und EPs werden da noch gar nicht groß behandelt. Fände ich gut!

**Comment by skerbis** [comment]
Aktuell beziehen sie sich alle auf den Table Manager  - ja

**Comment by skerbis** [comment]
Mittlerweile nicht mehr

**Comment by alexplusde** [comment]
¯\_(ツ)_/¯ habe momentan nicht so viel Spaß an der Doku, fühle mich mit der Betreuung im Slack-Channel schon genug ausgelastet. Vielleicht möchte ja @marcohanke ?

**Comment by marcohanke** [comment]
Sollen die alle komplett in die Doku?

**Comment by alexplusde** [comment]
Ja - einen neuen Navigationspunkt anlegen, dort einfügen.

**Comment by alexplusde** [comment]
Hier ist leider kein Engagement entstanden. Bei Bedarf soll's einfach jemand™ irgendwann® tun.

**Comment by skerbis** [comment]
> Hier ist leider kein Engagement entstanden 
?
@alexplusde das sehe ich anders

**Comment by alexplusde** [comment]
Es hat niemand übertragen. Es möchte wohl auch keiner. Ich denke, ein Issue dazu ist überflüssig.
