### ISSUE TITLE
Schlechte Google-Platzierung

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/tricks#148]
Trotz eindeutiger Suchbegriffe finde ich oft keine Tricks-Seite bei Google. Ich würde mir das gerne Mal anschauen, dazu bräuchte ich aber eine Authentifizierung in der Google Search Console.

Wäre es möglich, einen Meta-Tag zu hinterlegen oder sogar einen txt-Record an der (Sub-)Domain?

**Comment by skerbis** [comment]
Kann ich nicht bestätigen.

**Comment by schuer** [comment]
@alexplusde Meta-Tag kannst du hier einbringen: https://github.com/FriendsOfREDAXO/tricks/blob/master/_includes/head.html

**Comment by alexplusde** [comment]
Thx
