### ISSUE TITLE
Navigation/Kategorien Problem > Kategorien-Inhalte werden nicht angezeigt > Fehlerseite

### ISSUE THREAD

**Issue by Geri2017** [FriendsOfREDAXO/tricks#149]
## 1. Problem
Wer die **Basis-Demo** installiert und entsprechend anpasst, könnte bei individuellen Änderungen auf ein späteres, mögliches Problem stoßen: einige Kategorien werden nicht mehr angezeigt, obwohl diese in der Navigation zu sehen sind.
Meistens entsteht das Problem erst dann, wenn Änderungen in den Metadaten vorgenommen werden.
Dort werden beim ersten Speichern die in der Basis-Demo hinterlegten Werte `art_online_from` und `art_online_to` gespeichert.
Erst dann greifen die im System hinterlegten Parameter und sperren die Inhalte der Kategorien und verweisen brav auf die Fehlerseite.

## 2. Problem lösen
Wenn man die Funktion `Online für einen bestimmten Zeitraum` nicht nutzen will, sollte man 
folgende Anpassungen vornehmen:

### 2.2 Template Header anpassen
Alle Einträge bis 
```
rex::setProperty('tabs', new ArrayIterator());
``` 
löschen

### 2.3 Template Navigation anpassen
Folgende Zeilen löschen
```
    	$category_is_visible = true;

    	if ($lev1->getValue('art_online_from') != '' && $lev1->getValue('art_online_from') > time()) { $category_is_visible = false; }

    	if ($lev1->getValue('art_online_to') != '' && $lev1->getValue('art_online_to') < time()) { $category_is_visible = false; }

```
und statt (alt)>
```
if ($lev1->isOnline(true) && (!in_array($lev1->getId(), $hidden_ids)) && $category_is_visible == true)
```
neu >
```
if ($lev1->isOnline(true) && (!in_array($lev1->getId(), $hidden_ids)))
```

### 2.4 Metainfos anpassen
`art_online_from` und `art_online_to` löschen

# Damit müsste dann alles wieder funktionieren 👍 

#### Danke an @marcohanke 🥇 und @gharlan 🥇 
https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1558521311217700?thread_ts=1558452020.161600&cid=C1BAXLN2F

**Comment by skerbis** [comment]
@Geri2017 kannst du den Trick als PR einreichen?

**Comment by Geri2017** [comment]
Wo genau kann ich den PR aufrufen?

**Comment by alexplusde** [comment]
Mindestens müsste der Inhalt formuliert hier reingestellt werden, da die verlinkte Diskussion aus Slack in einigen Tagen verschwinden wird.

**Comment by Geri2017** [comment]
Original Thread:
```
"Portierte und umgestaltete alte R4 auf R5 mit yYRewrite >
Bisher alles wunderbar, plötzlich zeigt das System Fehlerseiten an, obwohl die Kategorien online sind…
Was habe ich falsch gemacht?
R5.7 / PHP 7.2.18 (bearbeitet)"
> .htaccess korrekt
> kein YCom installiert, keine eigenen URL-Schemen definiert
> vorher keine eigenen Urls definiert, kein Seo42 oder ä.
> Wenn Seitennamen umbenannt werden, dann geht´s
> browsercache löschen hilft auch nicht
> Abmeldung aus Backend (oder anderer Browser) > geht nix mehr
> Eine einzige Kat funktioniert, Rest leider nicht
> kein Mountpoint in yrewrite gesetzt
> Inkognito-Modus geht auch nicht
> "Klingt aber so, als ob vielleicht im alten Template das konvertiert wurde, etwas gesperrt wird."
> "War in R4 die Community-Edition? Dann werden vielleicht Rechte in einem Template abgefragt, die es nicht mehr gibt." 
> Es wurde nichts konvertiert, einfach per copy/paste die Inhalte rüber
> Seite komplett neu aufgesetzt
> die Templates sind aus der Basis-Demo R5
> "Und zur Sicherheit unter R5 lief schon mal alles? Auch abgemeldet?" >> JA
> Setup neu durchlaufen -> keine Änderung
> "Wobei ... Mal forciert die pathlist aus dem Cache entfernen wäre eine Idee. Vielleicht hält die sich ja hartnäckig"
> Seite läuft auch ohne yrewrite nicht
> YRewrite deinstalliert > installiert geht trotzdem nicht
> Änderung der Altlasten im Template
```

**Comment by polarpixel** [comment]
Ich habe dieses Issue erst jetzt wahrgenommen, es hängt eigentlich mit der Demo zusammen und sollte dort behandelt werden. Ich hab das auf dem Schirm und werde es in die nächste Version einareiten, siehe hier:
https://github.com/FriendsOfREDAXO/demo_base/issues/74

Das Issue hier schließe ich deswegen.

**Comment by Geri2017** [comment]
Danke :-)
