### ISSUE TITLE
Fehlermeldung: `Argument 1 passed to rex_yform::getFieldName()...` > Falsche PHP Version

### ISSUE THREAD

**Issue by Geri2017** [FriendsOfREDAXO/tricks#150]
Falls jemand den Fehler 
```
Argument 1 passed to rex_yform::getFieldName() must be an instance of string, string given, ......
```
angezeigt bekommt, liegt das nur an der falschen **PHP Version**.

Passiert oft bei updates von alten REX4 Versionen auf REX5 mit PHP upgrade von <=5.6 auf =>7.2.

**Comment by alexplusde** [comment]
Was heißt „falsche PHP-Version“ bei dir? Warum sollte es falsch sein, REDAXO 5 mit PHP 7 zu betreiben?

**Comment by skerbis** [comment]
Verstehe den Beitrag nicht, @Geri2017 kannst du das etwas genauer erläutern?

**Comment by Geri2017** [comment]
Es geht um eine Umstellung/Upgrade von einer REX4 auf REX5 incl. Umstellung/Upgrade von PHP 5.x auf 7.2. 
Die Seite wurde auf einer älteren PHP installiert und erzeugte einfach den Fehler, weil PHP noch nicht im System umgestellt wurde. 
Die Error-Meldung `Argument 1 passed to rex_yform::getFieldName() must be an instance of string, string given` ist einfach irreführend, weil es nichts mit YForm zu tun hat, sondern mit der falschen PHP Einstellung.

Kacke… zu warm um zu erklären… ??? ... dicker Haufen .... jetzt besser? ... oder einfach nicht interessant genug?

**Comment by alexplusde** [comment]
Wie hast du YForm installiert, wenn die PHP-Version verkehrt ist? Dazu hättest du gar nicht kommen dürfen auf ordnungsgemäßem Wege

**Comment by Geri2017** [comment]
Auf Testserver mit richtiger PHP Einstellung installiert, dann übertragen, aber PHP Version nicht korrigiert.

**Comment by skerbis** [comment]
Ich weiß nicht ob man das als Trick einstufen kann. Ist wohl eher sowas für eine Fehlersammlung.

**Comment by alexplusde** [comment]
In der htaccess nicht korrigiert?

**Comment by skerbis** [comment]
sehe hier keinen Trick. Gerne als Versionscheck-Issue bei YForm oder REDAXO einreichen.
