### ISSUE TITLE
Addon properties - Startseite eines Addons zur Laufzeit verändern

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/tricks#153]
@gharlan 

> Ich hab es gerade mal im Cronjob-Addon als Beispiel getestet. In der dortigen boot.php habe ich dies hinzugefügt:
```
$page = $this->getProperty('page');
$page['href'] = ['page' => 'cronjob/log'];
$this->setProperty('page', $page);

```

> Wenn ich nun in das Addon gehe, lande ich direkt auf der zweiten Subpage, der Logausgabe. Und die Subpage ist dann auch aktiv.

Gewünscht von @dpf-dd

**Comment by skerbis** [comment]
@alexplusde Da ergänzen https://github.com/FriendsOfREDAXO/tricks/blob/master/_docs/backend/backend_snippets.md

Obwohl ich denke die Beispiele sollten ausreichend sein
