### ISSUE TITLE
Standard-Wert für status beim Erstellen eines Artikels

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/tricks#158]
"gesperrt" (status=2) mit accessdenied als default für einen neuen Artikel. Oder beim Erstellen einer neuen Website mit vielen Artikeln status=1, um es gleich zu veröffentlichen.

```
<?php

rex_extension::register('ART_ADDED', "setDefaultStatus");

function setDefaultStatus($ep)
{
    rex_sql::factory()->setQuery("UPDATE rex_article SET status = ? WHERE id = ?", [2, $ep->getParams()['id']]);
}
```

Könnte man nun noch um eine eigene Einstellung erweitern, z.B. via "Globale Einstellungen" oder im Project-Addon. Ich versuche mich mal an einer Anleitung, bis dahin ist die Lösung hier geparkt.

**Comment by skerbis** [comment]
@alexplusde und @DanielWeitenauer  wäre das nicht was für das Structure_Tweaks - Addon?

**Comment by alexplusde** [comment]
Schon, leider konnte ich bisher nicht erfahren, wie man an die Liste verfügbarer Status-Werte kommt.

**Comment by DanielWeitenauer** [comment]
Finde ich gut. 

@alexplusde diese Methoden geben die Status-Werte zurück:
```
rex_category_service::statusTypes();
rex_article_service::statusTypes();
```

**Comment by alexplusde** [comment]
Ist als Issue dort angelegt, gehört nicht mehr in die Tricks imho
