### ISSUE TITLE
YForm xlsx import

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/tricks#162]
Dieses Issue als Trick übernehmen
https://github.com/yakamara/redaxo_yform/issues/616

**Comment by skerbis** [comment]
@alexplusde gerne

**Comment by alexplusde** [comment]
Keine Lust mehr.

**Comment by 191977** [comment]
Sagt mir was zu tun ist und ich gebe mein Bestes!

**Comment by alexplusde** [comment]
> Dieses Issue als Trick übernehmen
https://github.com/yakamara/redaxo_yform/issues/616

**Comment by 191977** [comment]
Habe mich mal dran versucht. Wenn man auf github die Seite bearbeitet hat man ja keine Möglichkeit für ne Vorschau oder? pr ist raus, aber keine Ahnung ob das so passt...

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/tricks/pull/201
