### ISSUE TITLE
Sprunganker defekt

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/tricks#171]
https://www.redaxo.org/doku/master/listen#setcolumnformat

funktioniert nicht, Fehler in der JS-Browserconsole.

**Comment by skerbis** [comment]
Falsches Repo @alexplusde  ?

**Comment by alexplusde** [comment]
Goddamnit, ich war davor auf der Tricksseite und habe nicht gemerkt, dass ich auf den Docs bin.
