### ISSUE TITLE
diverse Tricks für yform

### ISSUE THREAD

**Issue by rotzek** [FriendsOfREDAXO/tricks#18]
YFom 'widget' mit dem man im modul yform tabelleneinträge a la medialist oder linklist auswählen kann
Eingabe:
`REX_YFORM_TABLE_DATA[id=1 output="widget" table="rex_yform_table" field="field_a,'/',field_b"]`
Ausgabe
`$item = yform_table::query()->findId('REX_VALUE[1]');`

`text|geburtstag|Geburtstag*|||#required:required|#grid:,datepicker`

die Zwischen-Pipes kannst du übrigens weglassen. mit der `#`-Notation kann man allgemein einzelne Elemente auch überspringen, da man mit `#` die Keys explizit angibt.

`text|geburtstag|Geburtstag*|#required:required|#grid:,datepicker`

`text|vorname|Vorname*|#attributes:{"required":"","autofocus":"","data-yform":"pipe"}` 
über attributes kann man dem element alles mitgeben was man möchte

das ist in php auch geschmeidig: `$f->setValue('text|vorname|Vorname*|#attributes:{"required":"","autofocus":"","data-yform":"pipe"}');`

**Comment by skerbis** [comment]
Thema für yform docs
