### ISSUE TITLE
Geschütze Dateien mit YCom Problem mit .htaccess

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/tricks#2]
Ich muss leider noch was melden ;-(
Mit der Zeile `RewriteRule ^/?media/(.*\.(pdf|xlsx|xls|ppt|docx|pptx|rar|mpp|eps|txt|rtf|pub|pubx|doc|zip))$ /index.php?fileName=$1 [L]
` in der .htaccess lassen sich keine xls, doc, docx, ... Dateien mehr am iPad Anzeigen. Es sind nur noch wirre Zeichen zu sehen. Nehme ich die Zeile raus, funktioniert alles wieder ...

**Comment by skerbis** [comment]
Was meinst Du mit wirren Zeichen?

**Comment by marcohanke** [comment]
![docx-datei](https://cloud.githubusercontent.com/assets/2425981/18778098/f9c960b4-8172-11e6-984c-00c91fe4fb9a.jpg)

**Comment by skerbis** [comment]
Nach REX_TEMPLATE[6] darf keine Leerzeile oder Leerzeichen sein.
Ich habe das mal ebend bei Dir korrigiert. Bitte prüfen.

**Comment by marcohanke** [comment]
Nach wie vor das gleiche Problem ...
Darf nach REX_TEMPLATE generell keine Leerzeile sein ????

**Comment by staabm** [comment]
> Darf nach REX_TEMPLATE generell keine Leerzeile sein ????

nur in binär-ausgaben (wie pdfs). funktionieren die gleichen pdfs im offiziellen adobe reader und in normalen desktop browsern?

**Comment by staabm** [comment]
sowas passiert z.b. auch wenn php warnungen sich mit dem pdf stream vermischen

**Comment by marcohanke** [comment]
Am Desktop läufts

**Comment by staabm** [comment]
> Am Desktop läufts

x-browser? oder im adobe reader?

**Comment by marcohanke** [comment]
Direkt im Browser

**Comment by marcohanke** [comment]
PDF wird im Browser angezeigt, docx wird zum Download angeboten.

**Comment by skerbis** [comment]
Das scheint mir irgendwie systemspezifisch zu sein. Auf meiner Website geht es in iOS. Ich bekomme angeboten es in Pages zu öffnen.

**Comment by marcohanke** [comment]
Komisch, wenn ich die RewwriteRule raus nehme, bekomme ich die Datei angezeigt und die Auswahl "in Books öffnen". Wenn sie drin ist, kommt genanntes Problem. Nach Rücksprache mit dem Provider kann modrewrite doch "nur" Links umschreiben, ich wüsste nicht was ich da am System anpassen soll...

**Comment by skerbis** [comment]
@staabm im Code ist ein rex_response::cleanOutputBuffers(); eingesetzt. Sollte doch eigentlich eine saubere Ausgabe erfolgen? ... Merkwürdig ist, dass das Problem nicht auf Desktop-Systemen auftritt.

**Comment by skerbis** [comment]
Es hatte sich bei Copy & Paste ein exit; eingeschlichen es sollte aber exit(); heißen ... hoffe das war's.

**Comment by marcohanke** [comment]
Leider war’s das immer noch nicht ;-(

**Comment by skerbis** [comment]
.... hat sich erledigt ... war ein Kommentar an falscher Stelle im Template der Website
