### ISSUE TITLE
REDAXO 5.3 eigene CSS fürs Backend - Workaround

### ISSUE THREAD

**Issue by darwin26** [FriendsOfREDAXO/tricks#20]
Da in R53 die be_styles CSS Rules am Ende stehen, werden die eigenen CSS Rules überschrieben. Vorläufiger Workaround (Danke @tbaddade) zum Einbinden eigener CSS Styles:

```
rex_extension::register('PACKAGES_INCLUDED', function () {
        rex_view::addCssFile($this->getAssetsUrl('deine-styles.css'));
});
```
Könnte z.B. in der boot.php im /project/ notiert werden.

**Comment by alexplusde** [comment]
@tyrant88 macht es so, dass er sich das be_style-redaxo-Plugin kopiert, abwandelt und dann aktiviert.

Außerdem gibt's doch dafür auch das theme-Addon, oder nicht?

**Comment by staabm** [comment]
@tbaddade warum wurde die reihenfolge der css datei includes in 5.3 geändert?

**Comment by tbaddade** [comment]
@staabm siehe

https://github.com/tbaddade/redaxo_watson/issues/17#issuecomment-279817453
https://github.com/redaxo/redaxo/issues/1046

**Comment by tyrant88** [comment]
Meine tollen Backend-Anpassungen sind mir gestern nach dem Update um die Ohren geflogen, zum Glück war das noch nicht live beim Kunden.

 
 
Von: Thomas Blum [mailto:notifications@github.com] 
Gesendet: Donnerstag, 16. Februar 2017 09:21
An: FriendsOfREDAXO/tricks
Cc: Norbert Micheel; Mention
Betreff: Re: [FriendsOfREDAXO/tricks] REDAXO 5.3 eigene CSS fürs Backend - Workaround (#20)

 
@staabm siehe

tbaddade/redaxo_watson#17 (comment)
redaxo/redaxo#1046

**Comment by tyrant88** [comment]
```
.rex-nav-main {
    background-color: #fff !important;
}
.navbar-default {
    background-color: #64ad33;
}
```
Ich musste jetzt `!important` verwenden, damit "main" wieder "default" überschreibt.

Vielleicht bin ich ja naiv, aber wieso sind eigentlich nicht alle styles im plugin?

**Comment by staabm** [comment]
@tyrant88 wir werden zunächst die urspr. "problematische" Änderung reverten und schauen wie wir dann das urspr. problem lösen (gibt nen hotfix release für be_style demnächst).

**Comment by staabm** [comment]
Bitte testen, sollte mit dem be_style update von gestern nacht nicht mehr passieren

**Comment by darwin26** [comment]
Nach dem update des Addons be_style (2.2.1) kann man wieder via
`rex_view::addCssFile($this->getAssetsUrl('ipro_modul.css'));`
eigen CSS einbinden und benötigt den Workaround nicht mehr. Danke @staabm

**Comment by staabm** [comment]
ok, dann würde ich hier das issue schließen?

**Comment by tyrant88** [comment]
Ja, die styles funktionieren wieder so wie man es erwarten würde.
