### ISSUE TITLE
Editor-Einstellungen VSCode

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/tricks#207]
Damit das nicht verloren geht
https://github.com/redaxo/redaxo/pull/3629#issuecomment-629653502

Für VSCode muss man sich die YAML extension (https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) installieren, und dann dies in die settings.json eintragen:

    "yaml.schemas": {
        "./redaxo/src/core/schemas/config.json": ["/redaxo/data/core/config.yml"],
        "./redaxo/src/core/schemas/package.json": ["package.yml"],
    }

**Comment by crydotsnake** [comment]
Diese Extension ist auch noch zu Empfehlen: https://marketplace.visualstudio.com/items?itemName=bierner.github-markdown-preview

**Comment by crydotsnake** [comment]
@aeberhard Möchtest du Quasi ein Trick anlegen, oder ein Doku Kapitel schreiben wie man sich seinen Editor am besten Konfigurieren kann um bei der Tricks seite Mitzuwirken was yml dateien angeht?,

**Comment by alexplusde** [comment]
Ich hätte da auch Vorschläge und hatte vor, einen Screencast zu machen... Kann aber noch nicht sagen, wann ich dazu komme.

**Comment by crydotsnake** [comment]
Zu was genau? @alexplusde

**Comment by aeberhard** [comment]
@crydotsnake Werde ich bei Gelegenheit machen.

- YAML-Extension
- PHP CS Fixer mit den REDAXO-Vorgaben

@schuer sowas bei "Diverses" reinpacken oder neuen Hauptmenüpunkt!?

**Comment by schuer** [comment]
> @schuer sowas bei "Diverses" reinpacken oder neuen Hauptmenüpunkt!?

Mir ist alles recht; Ich bin den Tricks inhaltlich nicht allzu verbunden. :)

**Comment by skerbis** [comment]
Neuer Punkt Development @aeberhard ?

**Comment by aeberhard** [comment]
@skerbis jo das ist gut!
würde eine editor-config.md erstellen mit obigen Punkten zu VSCode
Evtl. kann dann ja noch jemand was zu PhpStorm beitragen.

**Comment by alexplusde** [comment]
mit dem config-sync-Plugin für VSCode könntest du auch ein gist nutzen, das man sich direkt abrufen kann.

**Comment by aeberhard** [comment]
@alexplusde ich weiss nicht ob das Sinn macht. bei Windoof sind halt die Pfade zu speziell. (Userid im Pfadnamen)
Ich schreibe die wenigen Config-Einstellungen lieber hier rein zum Copypasten.

**Comment by alexplusde** [comment]
Ich kann diese Erweiterungen noch empfehlen

**VS Code UI Deutsch**
ms-ceintl.vscode-language-pack-de

**Übergreifende Einstellungen**
shan.code-settings-sync

**Git**
eamodio.gitlens


**SFTP/SSH**
liximomo.sftp

**Doku: Rechtschreibkorrektur / Markdown**
adamvoss.vscode-languagetool
adamvoss.vscode-languagetool-en
adamvoss.vscode-languagetool-de
davidanson.vscode-markdownlint
bierner.github-markdown-preview

**PHP**
junstyle.php-cs-fixer
felixfbecker.php-intellisense
ikappas.phpcs

**Code Formatter**
esbenp.prettier-vscode

**Comment by crydotsnake** [comment]
Ich habe mein Setup hier Dokumentiert: https://github.com/crydotsnake/my-vscode-setup

**Comment by skerbis** [comment]
Dank an @aeberhard , @alexplusde , @crydotsnake
