### ISSUE TITLE
YForm be_manager_relation select aufhübschen

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/tricks#22]
```
$('#yform-formular-tag').find('select').find('option').each(function () {
	var $this = $(this);
	$this.text($this.text().replace(/\[id=\d+\]/g, ''));
}).end().select2();
```
Bei den be_manager_relation selects wird im Optionstext ` id=xx` ausgegeben. Das Snippet entfernt den id Teil und macht danach ein Select2 draus.

**Comment by skerbis** [comment]
Da select 2 nur als Plugin geliefert wird, besser ein Bootstrap Select draus machen, das ist im Core enthalten. https://silviomoreto.github.io/bootstrap-select/examples/

**Comment by IngoWinter** [comment]
Der macht primär hübsch. Ich brauch aber Funktionen, und da kann er wesentlich weniger als select2. Aber sonst einfach `.select()` durch `.selectpicker()` ersetzen, ist ja kein Ding.

**Comment by skerbis** [comment]
War nur ein Hinweis

**Comment by IngoWinter** [comment]
Und vielen Dank dafür - hatte ich bisher nicht auf dem Schirm :)

**Comment by skerbis** [comment]
Bevor ich hier dicht mache, hier weitere Infos: 
https://github.com/FriendsOfREDAXO/tricks/blob/master/backend_sytling-select.md
