### ISSUE TITLE
Apply Coding Standard on PHP Snippets in Markdown Files

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/tricks#228]
Für einheitlichen code style in den markdown dateien.. hat jmd lust?

Anleitung https://tomasvotruba.com/blog/2020/09/14/how-to-apply-coding-standard-on-php-snippets-in-markdown-files/

**Comment by eaCe** [comment]
@staabm ich wollte es geradte probieren. Das Package aus dem Beitrag ist Discontinued, dann habe ich das gefunden: 
https://github.com/easy-coding-standard/easy-coding-standard/commit/3754762609121f6f5740a2482b66c3235651ee79
Es scheint leider nicht mehr supported zu sein. 
Ich habe auch noch kein anderes gefinden.

**Comment by staabm** [comment]
Danke 🙏
