### ISSUE TITLE
YForm Best Practice für Tabellen- und Feldnamen

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/tricks#246]
Grobes Inhaltsverzeichnis:

(bitte auch Diskussion unter https://github.com/yakamara/redaxo_yform_docs/issues/61 beachten/berücksichtigen)

Tabellen-Präfix
a. rex_yf_ Für Datentabellen
b. rex_yfr_tabelle1_tabelle2 für Relationstabellen, als Name „Tabelle 1 ↔ Tabelle 2“
c. rex_yfv_ für Views: Um Views zu erstellen muss der Hoster dem Nutzer das passende DB-User-Recht freischalten
Tabellen- und Feldnamen möglichst in Englisch
a. team für Mitarbeiter / Team / Personen
b. messages für Kontaktformulare
c. products für Produkte / Artikel etc.
d. events für kalendarische Daten (Termine, Veranstaltungen, etc.)
Tabellen erstellen
a. Aktiv JA
b. Sortierung zunächst id
c. Suche aktiv JA
d. Export erlauben JA
e. Import erlauben JA
f. Massenlöschung erlauben JA
g. Historie anlegen JA
Felder erstellen
a. firstname | text | für Vornamen
a. lastname | text | für Nachnamen
b. name | text | für Namen, Überschrfiften, Titel, Artikelnamen, etc.
b. name_$clang | text | für mehrsprachige Namen, Titel, Überschriften
c. status | checkbox | für online/nicht online
d. email | text | für E-Mails
e. image | be_media | für ein einzelnes Bild
f. images | be_media | für Bilder
g. description | textarea | für HTML-Text (Redactor)
h. createdate | datestamp | Zeitstempel
i. updatedate | datestamp | Zeitstempel
j. _id oder _ids als Suffix für Fremdschlüssel / Relationsschlüssel und SQL-Select
k. token | hashvalue | für einmalige Aktivierungscodes (bspw. E-Mail-Freischaltung)
l. Nach dem Felder-Erstellen die Sortierreihenfolge logisch einstellen (Datum DESC bei Terminen, Produkte, etc.) und ggf. Anzahl der Datensätze pro Seite anpassen
Validierungen
a. name | empty
b. email | empty + email
c. unique, wenn ein Feld oder eine Feld-Kombination als URL-Slug dient
d. Weitere Validierungen je nach Sinn und Zweck
i. Pflichtfelder -> empty
ii. URL-Felder -> unique
Objekt-Parameter
a. (ergänze ich noch)
Ausgabe (YOrm / MySQL)
a. (ergänze ich noch)

**Comment by skerbis** [comment]
Gerne hier diskutieren
https://github.com/orgs/FriendsOfREDAXO/discussions

**Comment by alxndr-w** [comment]
Da gibt's für mich nichts zu diskutieren.
