### ISSUE TITLE
YForm: Dataset-Export mit richtigen Umlauten für Excel

### ISSUE THREAD

**Issue by akrys** [FriendsOfREDAXO/tricks#25]
Ein Kunde bemängelte bei mir gerade falsche Umlaute beim Dataset-Export. Nach etwas längerem Suchen habe ich den Extension-Point `YFORM_DATA_TABLE_EXPORT` gefunden, mit dem man die Daten bearbeiten kann, bevor sie in CSV konvertiert werden.

```php
rex_extension::register('YFORM_DATA_TABLE_EXPORT', function(rex_extension_point $params)
{
	$subject = $params->getSubject();

	foreach ($subject as $key => $row) {
		foreach ($row as $column => $value) {
			$subject[$key][mb_convert_encoding($column, 'ISO-8859-1')] = mb_convert_encoding($value, 'ISO-8859-1');
		}
	}
	return $subject;
});
```

Ich müsste das textlich noch etwas feiner ausarbeiten, daher zunächst nur als Issue.

**Comment by alexplusde** [comment]
Hab Dank, das konnte ich gerade sehr gut gebrauchen.

**Comment by alexplusde** [comment]
@staabm Redaxo 5 mit UTF8 erzeugt eine UTF8-CSV-Datei. Excel erwartet jedoch ISO.

**Comment by staabm** [comment]
ich kann mir nicht vorstellen dass Excel nicht mit UTF8 umgehen kann.. da fehlt sicher die UTF8 information in der Datei irgendwo..

**Comment by alexplusde** [comment]
@staabm Excel kann mit UTF8 in CSV umgehen, sofern dies als Datenimport in ein Tabellenblatt geschieht. Beim regulären "Doppelklick" auf die CSV-Datei wird diese von Haus aus als ISO-Datei interpretiert.

**Comment by skerbis** [comment]
Das öffnen einer CSV in Excel ist grundsätzlich nicht zu empfehlen. Da Excel es ohnehin nicht interpretieren kann, wenn man dem Programm nicht das Trennzeichen mitteilt. 
Open/Libre-Office und Apple-Numbers sind da weitaus schlauer.

**Comment by akrys** [comment]
Das mag durchaus sein. Wenn ich als Entwickler die Daten exportiere, habe ich natürlich Einfluss darauf, wie ich die Datei öffne. Excel ist da sowieso nie die erste Wahl.

Wenn der Kunde das aber selber macht (bzw. machen soll), passiert reflexartig folgendes:
- die Datei wird geladen
- es wird doppelt drauf geklickt

Doppelt drauf klicken bedeutet in 99% der Fälle: Excel öffnet sich und versucht, die Datei darzustellen. Meist mit mäßigem Erfolg, wie wir alle wissen. Dem Kunden ist es dann auch egal, warum das schlecht ist und warum man das so nicht machen solle. Für ihn muss es einfach funktionieren. (Der Umweg über neue Datei anlegen, Import aufrufen, Einstellungen vornehmen, öffnen funktioniert zwar, verliert in Sachen Komfort aber kolosal gegen den einfachen Doppelklick)

Außerdem nutzen Kunden sehr oft Windows. (zu oft für meinen Geschmack, steht aber hier nicht zur Debatte) Da fällt Numbers als Alternative schon mal per se raus. Libre-Office kann man durchaus empfehlen, aber ob die IT-Abteilung des Kunden, sich darauf einlässt, es zu installiert und später auch mit Updates zu versorgen, steht auf einem ganz anderen Blatt. Zumal es ja nur dazu da ist, dass ein Mitarbeiter richtig mit CSV-Dateien arbeiten kann.
Im Regelfall kann man davon ausgehen, dass das nicht der Fall ist.

Daher habe ich den Tipp aus der Trickkiste hier mal als allerletzte Notlösung hinterlegt. Es ist natürlich sehr unsauber und sehr unschön. Das kann man natürlich noch weiter durchdiskutieren. Es bringt am Ende des Tages aber nichts. Der Kunde eine saubere Darstellung seiner Daten haben. Und zwar ohne den Export der Daten jedes mal seinem Dienstleister beantragen zu müssen.

**Comment by alexplusde** [comment]
Das sei im neusten YForm bereits gefixt.
https://github.com/yakamara/redaxo_yform/commit/d36baf2873d7b3fffe5fe6224079c075fc83a227

**Comment by skerbis** [comment]
ist das der Fall @alexplusde , kann das hier zu?

**Comment by alexplusde** [comment]
ungetestet

**Comment by alexplusde** [comment]
getestet ;)
