### ISSUE TITLE
Template: Aus dem Frontend heraus in den Bearbeiten-Modus gehen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/tricks#26]
## Artikel bearbeiten
```
<?php if(rex_backend_login::hasSession()) { ?>
  <a href="/redaxo/index.php?page=content/edit&article_id=REX_ARTICLE[field=id]&mode=edit">bearbeiten</a>
<?php } ?>
```

## Erläuterung
Als "Quick-and-Dirty-Lösung" zu einer Frontend-Edit-Alternative. Funktioniert nur, wenn man im Backend angemeldet ist.

Das könnte man auch mit Slices, Sidebars und Metadaten machen. Ich verwende das fortan in meinen Templates.

**Comment by skerbis** [comment]
besser mit rex_url::backendPage() , du weißt nie wo REDAXO installiert sein kann ;-)

**Comment by alexplusde** [comment]
Gute Anregung - wie genau schaut der Pfad dann aus? (nie benutzt)

**Comment by skerbis** [comment]
@alexplusde  - Sollte so aussehen:

```php 
rex_url::backendPage('content/edit',
                            [
                                'mode' => 'edit',
                                'clang' => rex_clang::getCurrentId(),
                                'article_id' => rex_article::getCurrentId()
                            ]
                        )
```

**Comment by skerbis** [comment]
ich mach mal zu hier
