### ISSUE TITLE
Neue Tipps & Tricks: Backups – Warum, wann und wie durchführen?

### ISSUE THREAD

**Issue by madiko** [FriendsOfREDAXO/tricks#264]
Ich ergänze die Tipps & Tricks mit einer Unterseite zum Backup und schlage vor, die neue(n) Seite(n) unter die "How to" zu nehmen. 

Inhalte:

### Empfohlener Prozess (Checkliste was wie nacheinander durchführen)
Praxisfall 1: aktuelles Portal (Sicherheitskopie)
Praxisfall 2: Übertragen auf eine lokale Instanz
Praxisfall 3: Übertragen auf eine neue Instanz

### Verschiedene Wege zum Backup (in Verbindung mit Theme und Developer AddOns)
a) Backup via Backup Addon (mit Tipps, was zu beachten wäre)
b) Backup via Adminer AddOn (inkl. Tipps)
c) Backup via Terminal (putty, cmd für WIN / Sequel Pro für Mac) mit den entsprechenden Befehlen

Für Wünsche, Anregungen, Fragen bin ich offen.

**Comment by christophboecker** [comment]
Moinsen,

nur mal so in den Raum geworfen: was spricht dagegen die Inhalte in der Backup-Doku einzubauen statt hier? https://redaxo.org/doku/main/backup, als neuen Unterpunkt "Anwendungsbeispiele"?

**Comment by madiko** [comment]
Moin Christoph, genau da würde ich gern einen Verweis einbauen. Leider komme ich im Core mit dem Backup AddOn noch nicht klar. Kannst Du mir in diesem von Dir auch verlinkten Ordner noch zeigen, wo genau ich die Änderungen einbringen kann? 

Siehe auch Slack: https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1630087418086700?thread_ts=1629880978.148700&cid=C1BAXLN2F

... und der Issue, den ich soeben eröffnete:
https://github.com/redaxo/redaxo/issues/4752

**Comment by christophboecker** [comment]
Hi,

die Doku ist in der Doku verlinkt: https://redaxo.org/doku/main/zusammenarbeit verweist auf https://github.com/redaxo/docs

**Comment by madiko** [comment]
Ooooooooooooops:

`$ git push origin issue264
remote: Permission to FriendsOfREDAXO/tricks.git denied to madiko.
fatal: unable to access 'https://github.com/FriendsOfREDAXO/tricks.git/': The requested URL returned error: 403
`

Muss ich noch freigeschaltet werden?
@christophboecker

**Comment by christophboecker** [comment]
Command line Zeugs? Keine Ahnung, nicht meine Welt.

Von meinem iPhone gesendet

**Comment by skerbis** [comment]
@madiko ein eigener Branch würde reichen.

**Comment by alxndr-w** [comment]
> Warum so umständlich?

Damit nicht Hinz und Kunz in den offiziellen, auf die Website gesyncten Docs arbeiten können.

Ich erachte das hier als nicht zielführend.

Vielleicht ergibt es mehr Sinn, sich erstmal mit dem Backup-Addon auseinanderzusetzen. Dass Backups sinnvoll und zu tun sind, kann man eigentlich auch in zwei Bauernregeln zusammenfassen: "Kein Backup, kein Mitleid." und "Nobody wants backup, everybody wants restore."

* Shared Hoster bieten oft einen 1-Klick-Download, aber nicht immer.
* Nicht alle gehen über Protokoll X (SSH, SFTP, ...) oder Programm X (FileZilla, WinSCP, whatever)
* Alle Dateien herunterladen oder auf dem Server vorher zippen - es gibt so viele unterschiedliche Präferenzen, die weder falsch noch "richtiger" als andere sind.
* Workflows wie mit YDeploy erfordern ganz andere Herangehensweisen an Backups.

Da jede Eventualität zu protokollieren ergibt keinen Sinn. Genauso wenig, bei Adam und Eva anzufangen. Dazu gibt's genug allgemeine Tutorials im Internet und Hilfeseiten bei den jeweiligen Hostern.

**Comment by alxndr-w** [comment]
> Warum so umständlich?

Damit nicht Hinz und Kunz in den offiziellen, auf die Website gesyncten Docs arbeiten können.

Vielleicht ergibt es mehr Sinn, sich erstmal mit dem Backup-Addon auseinanderzusetzen. Dass Backups sinnvoll und zu tun sind, kann man eigentlich auch in zwei Bauernregeln zusammenfassen: "Kein Backup, kein Mitleid." und "Nobody wants backup, everybody wants restore."

* Shared Hoster bieten oft einen 1-Klick-Download, aber nicht immer.
* Nicht alle gehen über Protokoll X (SSH, SFTP, ...) oder Programm X (FileZilla, WinSCP, whatever)

Da jede Eventualität zu protokollieren ergibt keinen Sinn. Genausowenig, bei Adam und Eva anzufangen.
