### ISSUE TITLE
Eigene Addons in der Backend Navigation oben plazieren

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/tricks#268]
In der package.yml des Addons notieren, in welchem Block es dargestellt werden soll:
```
page:
    title: 'My Addon'
    block: myaddon
```

In der boot.php des Addons prio und Überschrift für den Block festlegen:
```
rex_extension::register('PAGE_NAVIGATION', function ($ep) {
    $subject = $ep->getSubject();
    $subject->setPrio('myaddon',1);
    $subject->setHeadline('myaddon','Ganz oben');
    $ep->setSubject($subject);
});
```

**Comment by alxndr-w** [comment]
Prio und Name lässt sich auch über die package.yml / de_de.lang festlegen, genauso wie umgekehrt via PHP der Block, in dem der Punkt ausgegeben wird. Hier müsste man den Trick eher unterscheiden zwischen programmatisch/zur Laufzeit, oder per package.yml

**Comment by IngoWinter** [comment]
Ich habe nicht rausgefunden, wie ich in der package.yml die prio des Blocks festlegen kann. Wenn das geht ist das natürlicht noch schicker :)

**Comment by IngoWinter** [comment]
Ahso. Ich glaube es liegt ein Missverständnis vor. Es geht um einen Block mit mehreren Pages, der oberhalb des Blocks "Hauptmenü" und "Addons" plaziert wird. Aktuell habe ich drei Addons, die in einem eigenen Block (wie die Community) ganz oben dargestellt werden.

**Comment by IngoWinter** [comment]
![ganzoben](https://user-images.githubusercontent.com/7223820/132869907-81f93426-48ba-4b60-9d06-6027436bce9a.png)

**Comment by alxndr-w** [comment]
Ich werde in den kommenden Tagen hier noch Senf dazugeben...

**Comment by IngoWinter** [comment]
https://github.com/FriendsOfREDAXO/tricks/pull/281

**Comment by alxndr-w** [comment]
Ups, da war was. Mein Beitrag, wie man etwas priorisiert, bspw. im Hauptmenü. https://github.com/alexplusde/qanda/blob/be2939ba5050c829f1780954b383f2882938827d/package.yml
