### ISSUE TITLE
Modul Tipp: Repeater

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/tricks#270]
Aus aktuellem Anlass habe ich ein Repeater Modul gebaut, das auf 2 Ebenen verschachtelt ist. 
Das habe ich bisher leider noch nicht mit MBlock hinbekommen (siehe https://github.com/FriendsOfREDAXO/mblock/issues/78#issuecomment-496260063).

Wenn Interesse besteht würde ich dafür einen Tipp schreiben.

Das Modul läuft mit Alpinejs, es hat mich einige Nerven gekostet, Alpinejs und pjax vertragen sich im Redaxo-Umfeld wohl nicht so gut... Nun läuft es, vermutlich kann man das aber noch eleganter schreiben.

Man kann Gruppen und Felder hinzufügen oder löschen, aber nicht verschieben. Das wäre sicher sinnvoll, habe ich aber noch nicht gebaut.

Ich hänge euch hier einfach mal ein gif dazu an.

![repeater](https://user-images.githubusercontent.com/2708231/135720119-947c6f80-d928-4377-84bc-e8fd35e9f0a7.gif)

**Comment by skerbis** [comment]
Gerne.

**Comment by eaCe** [comment]
@skerbis willst du das vielleicht zunächst gegentesten?

Ich habe ein paar Funktionen erweitert und das ganze etwas aufgehübscht (siehe Screenshot). 

![Bildschirmfoto am 2021-10-03 um 08 19 40](https://user-images.githubusercontent.com/2708231/135742529-924249bc-4c29-4eda-a8e9-d316425d5f46.png)

Zunächst muss Alpinejs eingebunden werden. 
Ich habe das einfach über das Project Addon gemacht...
```
if (rex::isBackend() && rex::getUser()) {
    rex_view::addJSFile('//unpkg.com/alpinejs', [rex_view::JS_DEFERED => true]);
}
```

Modul Input:
https://gist.github.com/eaCe/38186743b325ca5953cfc7858b47364f

Output zum testen:
```
<?php
$accordionItems = json_decode(html_entity_decode(REX_VALUE[1]));
echo '<pre>';
var_dump($accordionItems);
echo '</pre>';
?>
```

**Comment by skerbis** [comment]
Wie verhält es sich mit Widgets aus REDAXO und ggf. Texteditoren?

**Comment by skerbis** [comment]
Getestet und gut

**Comment by eaCe** [comment]
Für Widgets und Texteditoren muss man die Funktionalität natürlich erweitern.
Ich habe das erst mal nicht berücksichtigt. 

Wenn alle möglichen Felder genutzt werden sollen benötigt man diverse Helper Funktionen. Ich habe testweise mal ein Link-Feld eingebaut. Hierfür benötige ich eine rex_api_function und ein bisschen jQuery. Leider kann man keine jQuery Events in nativem JS einfangen.

Will sagen - es geht, braucht aber weiteren Code. Wenn man das ganze weiterspinnt wird eher ein Addon draus.

**Comment by skerbis** [comment]
Gut 👍 für den Trick ist’s doch schon super.

**Comment by eaCe** [comment]
Danke @skerbis
