### ISSUE TITLE
REDAXO Grundeinstellungen

### ISSUE THREAD

**Issue by madiko** [FriendsOfREDAXO/tricks#29]
Hallo,

ich fände eine Sammlung kleinerer "Hacks" rund um Grundeinstellungen super. Die Infos sind in der Doku teils sehr verstreut - eine Bündelung wäre super.

Ideen (mit zwei offenen Fragen):

**Paginierung für das Backend hochsetzen**
Wo im Code des Core? (Antwort interessiert mich auch)
Tipps und Anleitung: https://redaxo.org/doku/master/paginierung

**Medien-Pool**
Nach Auswahl des Mediums Popup des Medien-Pools automatisch schließen
? 

**Empfohlene AddOns**
Eine Sammlung an AddOns, die - neben den vom System mitgelieferten - geprüft und installiert werden sollten. Ich bin offen, meine Basics sind:
* E-Mail-Verschlüsselung
* Meta Infos
* out5
* PHPMailer
* YForm
* Multi-Domain (YRewrite oder x-core)

Danke und viele Grüße,
Franziska

**Comment by skerbis** [comment]
@madiko Solche Hacks können sicher sinnvoll sein, sehe ich jedoch eher als Umsetzung als Addon. 
Solche Hacks werden sicher sonst beim nächsten Update überschrieben. 
Eine Empfehlung für default Addons ist immer etwas schwierig, da sich die Projekte von Fall zu Fall doch sehr unterscheiden. 

Aber ein Fallbeispiel in dem man erklärt wie man ein Projekt aufgebaut hat und warum man sich für dieses oder jenes Addon entschieden hat, wäre mal was tolles. 
Gerne für die Doku: https://github.com/redaxo/docs

**Comment by skerbis** [comment]
@madiko in 5.4 wird die Paginierung an einigen Stellen hochgesetzt.

**Comment by skerbis** [comment]
Gerne Hierzu einen Trick schreiben @madiko - ich mach hier vorläufig zu.
