### ISSUE TITLE
Komplexe Navigation: Beispiel-Filter, der art_values in class="" oder data-value="" schreibt.

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/tricks#3]
Würde an der Stelle noch gut passen.

**Comment by alexplusde** [comment]
Danke, wurde von irgendwem ergänzt.

Noch eine Frage: Wenn ich in einem Navigationspunkt mich mit eigenem HTML-Output einhängen möchte, wie geht das? z.B. dass an der Stelle eine weitere Subnavigation ausgegeben wird, die mit YForm-Daten gespeist wird oder Teaser in einem sog. "Super Menü".

@schuer oder irgendwer?

**Comment by skerbis** [comment]
@alexplusde eigene Navi bauen: https://redaxo.org/doku/master/navigationen

**Comment by schuer** [comment]
Issue gehört nicht mehr zu Tricks und kann geschlossen werden, oder? Sonst gerne wieder öffnen.
