### ISSUE TITLE
Argumentationshilfe für / Vorteile von Redaxo

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/tricks#32]
https://github.com/FriendsOfREDAXO/tricks/blob/master/redaxo-argumentationshilfe.md in diesem Dokument habe ich mal angefangen, die Vorteile von REDAXO im Vergleich zu anderen CMS zusammenzutragen. 

Ergänzungen können von FOR-Mitgliedern direkt bearbeitet werden, nicht-FOR-Mitglieder können hier ihre Erfahrungen und weitere Argumente einfügen, dann werde ich sie in das Dokument schreiben.

todo: Backups
todo: Link im Tricks-Repository einfügen

**Comment by alexplusde** [comment]
Slack-Thread: https://friendsofredaxo.slack.com/messages/C1BAXLN2F/convo/C1BAXLN2F-1502706833.434501/

* Versionsupdates erscheinen derzeit Quartals-/Halbjahresweise
* Einsetzbar als Headless CMS http://t3n.de/news/headless-cms-im-vergleich-717022/
* Multidomainfähig
* Modularer Aufbau in Blöcken

**Comment by skerbis** [comment]
Passiert hier noch was? @alexplusde  oder warum ist es nicht in der Navi?

**Comment by alexplusde** [comment]
@skerbis oh, das habe ich komplett vergessen. 

Ich wollte, dass da nochmal jemand drüber geht und ggf. Ergänzungen vornimmt, die auch hier im Issue notiert sind.

Aber prinzipiell kann es bereits in die Navi verlinkt werden.

**Comment by skerbis** [comment]
@alexplusde machst du das bitte?

**Comment by skerbis** [comment]
@alexplusde ping

**Comment by alexplusde** [comment]
Danke. Das ist untergegangen, Notifications kann man in Github nicht als ungelesen markieren. Ich habs jetzt in meiner Lesezeichenleiste und damit auf dem Schirm.

**Comment by skerbis** [comment]
https://friendsofredaxo.github.io/tricks/redaxo-argumentationshilfe.html
