### ISSUE TITLE
Image URL bei Repeater ist defekt

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/tricks#325]
https://github.com/FriendsOfREDAXO/tricks/blame/main/_docs/module/einfacher_repeater.md

Die URL zum Bild selbst funktioniert, aber ist anscheinend nicht korrekt im MD file. Ich konnte den Fehler nicht identifizieren.

**Comment by eaCe** [comment]
Danke, da hat sich wohl etwas geändert.
