### ISSUE TITLE
AJAX mit rex_api SYNTAX error

### ISSUE THREAD

**Issue by nexus23** [FriendsOfREDAXO/tricks#34]
Der API URL Parameter ist
index.php?rex-api-call
Hin und wieder in der README falsch notiert
index.php?rex_api_call

Quelle: https://github.com/redaxo/dokumentation/blob/master/create_addon/api/README.md

**Comment by skerbis** [comment]
@nexus23 Es handelt sich hierbei nicht um die offizielle Doku. Diese findest Du hier: 
https://redaxo.org/doku/master und hier: https://github.com/redaxo/docs
