### ISSUE TITLE
Suchfunktion zeigt keine neuen Treffer

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/tricks#348]
**Description / Beschreibung**
Die algolia-Suche scheint nicht mehr die Tricks zu indexieren.

![image](https://github.com/FriendsOfREDAXO/tricks/assets/3855487/1a1e16a3-16fb-45b8-92a0-685bdb74053b)

**Comment by eaCe** [comment]
Stimmt, das Plugin funktioniert scheinbar nicht:
![grafik](https://github.com/FriendsOfREDAXO/tricks/assets/2708231/435c20e5-f57f-43b2-b24f-c6fdb01a81ec)

**Comment by eaCe** [comment]
> der crawler kommt immer freitags um 11 uhr vorbei. letzter crawl war dementsprechend am 10.11.
Warten wir mal ob Morgen was passiert, so lange mach ich hier zu, sollte sich nichts ändern mache ich wieder auf

**Comment by eaCe** [comment]
:tada:

![grafik](https://github.com/FriendsOfREDAXO/tricks/assets/2708231/774022a0-35f2-44a8-b5a1-170012873823)

**Comment by alxndr-w** [comment]
Wie das jetzt? :)

**Comment by alxndr-w** [comment]
Ah, den letzten Verlauf hat's mir nicht angezeigt. Vielen Dank.
