### ISSUE TITLE
Yform Hidden Fields

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/tricks#38]
Gregor Schrieb heute auf Slack [5:10 PM] 
Für tatsächliche `type=hidden`-Felder gibt es zwei Möglichkeiten:
1. `$yform->setValueField('hidden', array("termin_bearbeiten","1", 'REQUEST'));`
2. `$yform->setHiddenField('termin_bearbeiten', 1)`

Ersteres ist ein Value-Field, landet also auch in der DB etc.
Letzteres ist einfach nur ein Hidden-Feld im Formular, womit Yform aber ansonsten nichts weiter macht.
(Hoffe das ist so korrekt, bin mir gerade selbst nicht ganz sicher)

**Comment by staabm** [comment]
ist das irgendwas was in der yform doku erwähnt werden soll? oder was soll dieses issue bewirken/was ist das ziel/problem?

**Comment by gharlan** [comment]
/cc @alexplusde 
/refs https://github.com/yakamara/redaxo_yform_docs/issues/78

https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/yform_modul_values.md#hidden

@alexplusde den Hinweis dort könnte man vielleicht anpassen, der Umweg über ein `text`-Feld ist eigentlich notwendig.

**Comment by alexplusde** [comment]
@cukabeka für type=hidden-Felder gibt es nur eine Variante (nämlich dein 1.). Zweiteres ist eben nicht nur ein hidden-Feld im Formular. Es lässt sich sehr wohl in die DB schreiben, habe ich selbst gerade in Verwendung. 

Da doch jeder eine unterschiedliche Vorstellung von `hidden` und dessen Verwendung hat, werde ich mal ein paar Fallbeispiele in einen Doku-Anhang niederschreiben. (Bitte mich nicht darauf festlegen, wann genau)

**Comment by alexplusde** [comment]
@gharlan der Umweg ist **nicht** notwendig, meintest du, oder?

**Comment by gharlan** [comment]
Ups, ja! Habe es oben angepasst.

**Comment by alexplusde** [comment]
Also, ich verwende bspw. `$yform->setValueField('hidden', array("f_jahr_id",$jahr_id));` erfolgreich in einem Skript, in dem mir dann auch die Datenbank befüllt wird.

Was zur Debatte steht, auch in dem ursprünglichen Problem: Ich weiß nicht ob der Wert auch im Value-Speicher für die E-Mails landet: https://github.com/yakamara/redaxo_yform_docs/issues/78

**Comment by gharlan** [comment]
@alexplusde beachte den Zusatzparameter 'REQUEST', der macht daraus ein tatsächliches `type=hidden`-Feld (es wird dann auch der Wert genommen, der übertragen wird).

> Zweiteres ist eben nicht nur ein hidden-Feld im Formular. Es lässt sich sehr wohl in die DB schreiben, habe ich selbst gerade in Verwendung.

Das passiert automatisch, oder muss man dazu noch was extra machen?

**Comment by gharlan** [comment]
> Ich weiß nicht ob der Wert auch im Value-Speicher für die E-Mails landet

[Scheinbar ja](https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/hidden.php#L27)!

**Comment by alexplusde** [comment]
Dann muss in dem Modul von @greatif ein anderes Problem vorgelegen haben.

Ich habe noch nie bemerkt, dass mit einem REQUEST-Parameter ein `<input />`-Feld in der Ausgabe landet und kann das anhand des Aufbaus in https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/hidden.php nicht erkennen. Es wird ja nicht mal das passende Fragment verwendet.

**Comment by alexplusde** [comment]
> Das passiert automatisch, oder muss man dazu noch was extra machen?

Die action definieren und ein Feld in der Datenbank haben, aber eben nicht weitere Felder hinzufügen.

**Comment by gharlan** [comment]
Das mit REQUEST hat glaube ich eine zeit lang nicht funktioniert.
[Hier](https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/hidden.php#L24) wird es ausgegeben (wenn REQUEST gesetzt, siehe `if`).

**Comment by cukabeka** [comment]
@staabm ich hab das als weg gewählt, nützliche infos aus dem chat irgendwo zu dokumentieren, so dass das gold aus dem slack-channel nicht verloren geht ;)

**Comment by skerbis** [comment]
@alexplusde @dergel @gharlan ist das hetzt in der yform-Doku? Kann das Issue hier zu?

**Comment by alexplusde** [comment]
Es kann zu, weil es ein dazu ein Issue in den YForm Docs gibt.
