### ISSUE TITLE
Darstellungsprobleme in Tabellen wg. Word-Break Style

### ISSUE THREAD

**Issue by ischfr** [FriendsOfREDAXO/tricks#386]
Mir ist gerade aufgefallen, dass es auf dieser Tricks-Seite die Tabellen ziemlich deformiert:
https://friendsofredaxo.github.io/tricks/addons/consent_manager/google_consent_mode_v2
Die linke Spalte mit den Beschriftungen wird so weit zusammengeschoben, bis sie nur noch einen Buchstaben breit sind.
Sie werden dadurch unlesbar.

Das liegt anscheinend an folgender CSS-Anweisung:
https://github.com/FriendsOfREDAXO/tricks/blob/09d5de6a1aa8d345fc5fd729878bcad88f1d36f4/_sass/_content.scss#L10

Irgendeinen Grund wird es sicher mal gehabt haben, dass das hier eingesetzt wird. Evtl. gibt es irgendwo über-lange Code-Zeilen ohne Trennmöglichkeit?
Vielleicht kann man das per spezifischerem CSS-Selektor auf die Elemente beschränken, die es wirklich benötigen?

Ohne die Anweisung sehen die Tabellen jedenfalls besser aus.

**Comment by eaCe** [comment]
Dazu: https://github.com/FriendsOfREDAXO/tricks/pull/362#issuecomment-2151782265
