### ISSUE TITLE
Cheatsheet Snippet 4.1 Style

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/tricks#39]
Hi, 

wünsche mir für R5 für die Category, Article, Slice und Media etwas, das an das Cheatsheet im Webbude Style drankommt. Gerade die Auflistung aller API-Calls + ein paar Code-Snippets fand ich so nützlich, dass ich bis R4.7 immer noch das original PDF für R4.1 von @tbaddade zur Hand genommen habe:
![image](https://user-images.githubusercontent.com/688274/31554710-b4c20d30-b03e-11e7-9d6e-763f7725b455.png)
http://webbude.com/files/ooredaxo_41.pdf

Mein Vorschlag ist, sowas auch in den Tricks (oder der Doku) zu bauen.

**Comment by staabm** [comment]
Du darfst gerne so ein PDF erstellen und pflegen :-). PR welcome :-)

**Comment by cukabeka** [comment]
Hehe, vorerst wäre mir am liebsten, das einmal in der Doku oder in Tricks in Markdown/HTML zu finden. Bin allerdings tatsächlich mit der neuen Syntax noch nicht sehr firm. 
Außerdem gibt es doch bestimmt einen schlauen Weg, zumindest den Teil oben mit der API automatisch zu generieren, oder?

**Comment by skerbis** [comment]
Gerne anhand der API-Doku abarbeiten ;-) , da steht alles drin

**Comment by tbaddade** [comment]
@cukabeka Was du vermutlich suchst ist das hier (um beim Beispiel \rex_article zu bleiben)
https://redaxo.org/api/master/class-rex_article.html

**Comment by alexplusde** [comment]
jop, redaxo.org/api bietet eigentlich alles, was das Cheat Sheet so konnte, oder nicht?

**Comment by cukabeka** [comment]
IMHO allerdings lange nicht so übersichtlich und griffig wie es sein könnte. Um zB ArticleSlice oder die API für den Medienpool zu finden, muss man suchen - und als Noob wird man keine Chance haben, da was zu finden. Daher fände ich schön, wenn es für die wichtigsten API-Startpunkte eine handliche Doku gibt. 
Meine Vorschläge: 
- OOArticle
- OOCategory
- OOMedia
- OOArticleSlice
- OOMediaCategory
..gibts überhaupt sonst noch welche? 😆

**Comment by alexplusde** [comment]
@cukabeka InDesign kann recht gut mit XML und sowas umgehen. Wenn ich mal übrig Zeit habe, könnte ich dir eine Vorlage bauen, die du dann automatisch befüllen kannst.

Allerdings frage ich mich wirklich, wo der Mehrwert ist, das als PDF zu machen, wenn es ein HTML-Dokument auch tut. Und neben der API-Doku und der Redaxo-Doku frage ich mich, warum es da noch ein drittes Dokument Bedarf?

(Klar, ich musste mich auch erst umgewöhnen, die Funktionsweise der API-Doku zu verstehen. Aber geht schon.)

**Comment by skerbis** [comment]
Da habe ich lieber eine anständige Snippetsammlung in Snippetlab

**Comment by alexplusde** [comment]
@skerbis kenn ich nicht, was kann das?

**Comment by skerbis** [comment]
https://www.renfei.org/snippets-lab/

**Comment by alexplusde** [comment]
@skerbis gibt's nur für den Mac, fällt für mich raus.

**Comment by skerbis** [comment]
Hier gerne weitermachen
