### ISSUE TITLE
Quellcodeformatierung addons_project_class_pagination.md

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/tricks#4]
https://github.com/FriendsOfREDAXO/tricks/blob/master/addons_project_class_pagination.md
Quellcode bitte einrücken.. wie in Vorlage
@alexplusde

**Comment by alexplusde** [comment]
Hatte gerade einen PR gemacht, bei der die Quellcode-Formatierung auch nur über backticks ging. Irgendwas mach ich falsch?!

**Comment by skerbis** [comment]
@alexplusde  Hat sich erledigt - oder?

**Comment by alexplusde** [comment]
Ich weiß es nicht, ich verstehe nicht ganz, was ich machen muss.

**Comment by tbaddade** [comment]
Die `pager` Class aus dem Core kennt ihr?

**Comment by skerbis** [comment]
@alexplusde Anstelle der backticks  den Quellcode einrücken. Schaue Dir doch kurz die anderen Beispiele an. 
@tbaddade Davon gehört ja. Kannst Du Beispielcode für für die Erweiterung der Artikelliste (https://github.com/FriendsOfREDAXO/tricks/blob/master/modul_minibeispiel_artikelliste_mit_getarticles.md) oder sowas liefern ;-) ?

**Comment by alexplusde** [comment]
das hat bei mir nicht funktioniert, ich konnte den Quellcode nicht einrücken :/

**Comment by skerbis** [comment]
komisch ... hier im Github-Editor nicht? Welcher Browser?

**Comment by skerbis** [comment]
Ich habe das jetzt mal gemacht. Einfach in den Editor rein. Quellcode markieren und Einrücken.

**Comment by alexplusde** [comment]
Github-Editor, Windows, Chrome. Keine Ahnung, warum das nicht so wollte wie ich das wollte.

**Comment by alexplusde** [comment]
Danke jedenfalls :)
