### ISSUE TITLE
Ablauf des Workflows

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/tricks#46]
skerbis schrob:
> Und dann klären wir wie hier der Workflow abläuft

**Comment by skerbis** [comment]
Bislang habe ich darum gekümmert, das war auch gut so. Leider kann ich aber auch nicht alles testen, so dass wir uns einigen müssen, wie das Einpflegen und Testen neuer Inhalte erfolgt.  Wer testet was? Wer darf mergen? usw. Das Repo sollte ja für alle offen sein, direktes Commiting sollte wohl aber auch unterbunden werden.

**Comment by tbaddade** [comment]
**Vorschlag**

- Repo nur lesbar
- Änderungen via PRs
- Mergen sollte jedes :for: Mitglied können, außer der PR-Autor selbst (Damit haben wir zumindest ein Vier-Augen-Prinzip)

**Comment by staabm** [comment]
Es geht um den Workflow wie hier "tricks" veröffentlicht werden?

**Comment by tbaddade** [comment]
> Es geht um den Workflow wie hier "tricks" veröffentlicht werden?

Ja

**Comment by skerbis** [comment]
@tbaddade Guter Vorschlag. Ich bin dafür. Wichtig ist, dass im PR auch die README angepasst wird.

**Comment by skerbis** [comment]
Wer kann das Repo so einstellen, dass nur PRs erlaubt sind?

**Comment by schuer** [comment]
> Wer kann das Repo so einstellen, dass nur PRs erlaubt sind?

Done. Kannst du hier einstellen: https://github.com/FriendsOfREDAXO/tricks/settings/branches/master

**Comment by skerbis** [comment]
danke, aber ich kann es nicht, habe nicht die Rechte dazu @schuer
