### ISSUE TITLE
addons_project_add_own_js_css_files Ergänzung

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/tricks#47]
Auf Slack:

Frage von  Thorben
gibt es evtl. eine saubere Möglichkeit js/css nur dann einzubinden, wenn man sich auf einer Backendseite zu einem spezifischen Addon befindet? 

Antwort von Ingo
prüf in der boot.php des addons, ob in der url  der parameter page passt
added this PHP snippet: Unbenannt
```
if (rex::isBackend() && rex_get('page', 'string', '') === 'dein_addon')
{
  rex_view::addJsFile($this->getAssetsUrl('dein_addon.js'));
  rex_view::addCssFile($this->getAssetsUrl('dein_addon.css'));
}
```
ist etwas anders als auf https://github.com/FriendsOfREDAXO/tricks/blob/master/addons_project_add_own_js_css_files.md beschrieben. evtl gut, das noch hinzuzufügen.

**Comment by eaCe** [comment]
Etwas sauberer war die Antwort von Thomas, Thomas und Dirk

`if (rex_be_controller::getCurrentPage() == 'deinaddon/unterseite') { … }`

Also 

`if (rex::isBackend() && rex_be_controller::getCurrentPage() == 'deinaddon/unterseite') { … }`

**Comment by skerbis** [comment]
Das muss in die Doku, weniger in die Tricks.

**Comment by skerbis** [comment]
Ist nun in der regulären Doku. 
Danke für's sammeln: @eaCe @cukabeka   
https://github.com/redaxo/docs/blob/master/addon-assets.md
