### ISSUE TITLE
Copyright Bildquellen - Tutorial mit Modul, das Bildquellen ausgibt

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/tricks#52]
Wir haben ein kleines Modul gebastelt, das Bilder auf einer Seite "Bildquellen" ausgibt, wenn diese einen Copyright-Hinweis haben. Wäre das was für die Tricks?

**Inhalt des Tutorials**
1. nicht rechtsverbindlicher Hinweis, wann und wie Bildquellen angegeben werden müssen. (Eine Möglichkeit: Am Bild, hier vorgeschlagene Möglichkeit: extra Unterseite)
2. Hinweis, wo im Medienpool Copyright-Infos angegeben werden können / müssen
3. Modul-Beispielausgabe (siehe unten)
4. Passendes MedienManager-Profil anlegen

```
<section class="modul modul-text modul-copyright" id="modul-REX_SLICE_ID">
    <div class="wrapper">
        <?php
$images = array_filter(rex_sql::factory()->setDebug(0)->getArray('SELECT * FROM rex_media WHERE med_copyright != ""'));
foreach($images as $image) {?>
        <div class="layout-wrapper">
            <div class="content-wrapper">  
                <div class="modul-text-content">

                    <p><?php if($image['title']) { echo $image['title']; } else { echo "Ohne Titel"; } ?></p>
                    <p><?php echo $image['filename']; ?></p>
                    <p><?php echo $image['med_copyright']; ?></p>       
                </div>   

                <div class="image-wrapper image-right">
                    <div class="image-col">
                        <img src="/images/copyright_thumb/<?php echo $image['filename'];?>">
                    </div>
                </div>
            </div>
        </div>
        <?php } ?>
    </div>
</section>
```

**Comment by skerbis** [comment]
Bei vielen Quellangaben muss eine URL zum Original oder Autor angegeben werden. In der Modulsammlung gibt es bereits ein ähnliches Modul https://github.com/FriendsOfREDAXO/Modulsammlung/tree/master/lib/module/0200_bilder_copyright

**Comment by olien** [comment]
Danke @skerbis. Nur zur Info: Bei der Modulinstalltion wird einm MedienManagertyp und ein Metafeld angelegt. @alexplusde vielleicht magst Du es dir ja mal ansehen.
Verbesserungen sind natürlich sehr willkommen!

LG
Oliver

**Comment by alexplusde** [comment]
Ah, die Modulsammlung hab ich nicht so auf dem Schirm.

**Comment by olien** [comment]
Wäre auch schön, wenn die von einigen erweitert werden würde.
Ich glaube, dass die schon benutzt wird...
