### ISSUE TITLE
Vorschlag zur Ergänzung bei Module > Minibeispiele oder Snippets: Datum

### ISSUE THREAD

**Issue by madiko** [FriendsOfREDAXO/tricks#54]
```
// Artikel erstellt am
	$article_originalDate = rex_article::getCurrent()->getCreateDate();
	$article_created = date("d.m.Y", $article_originalDate);

// letzte Aktualisierung 
	$article_update_originalDate = rex_article::getCurrent()->getUpdateDate();
	$article_update = date("d.m.Y", $article_update_originalDate);
```

update: Fehlerkorrektur bei CreateDate. Danke für den Hinweis Thomas @tbaddade.

**Comment by tbaddade** [comment]
Da müsste eine Notice ausgegeben werden. `non well formed numeric`

Außerdem wird zweimal das Updatedate geholt. Auch wäre das Zwischenspeichern in der Variable unnötig. Und ist es überhaupt Trickswürdig?

**Comment by eaCe** [comment]
Wäre vielleicht etwas für eine Snippetsammlung. 

Ich speicher auch jede Variable immer zwischen... 

Zum ersten sollte es wohl dann anstatt `rex_article::getCurrent()->getUpdateDate();` eher `rex_article::getCurrent()->getCreateDate();` heißen.

Wirft bei mir keine Notice .

**Comment by skerbis** [comment]
ich denke @tbaddade bezieht sich auf Date… 
Alternativ kann man in  REDAXO auch `date = rex_formatter::date(strtotime(rex_article::getCurrent()->getUpdateDate()), 'datetime');` verwenden um ein schönes Datum zu erhalten

**Comment by IngoWinter** [comment]
Imho ist das weder ein notierenswertes Snippet noch ein Trick (zumindest in dieser Form im Kontext dieses Repos), Wenn wir hier für jede Methode der grundlegenden rex_ Klassen ein Snippet aufmachen, wird's schnell sehr unübersichtlich. Ebenfalls unübersichtlich finde ich den [Stub zu den Artikeleigenschaften](https://github.com/FriendsOfREDAXO/tricks/blob/master/howto_Artikeleigenschaften-Kategorieeigenschaften.md), den @skerbis gerade angelegt hat. Die aktuelle Formatierung bläht das ganze doch etwas auf.

Im [Nachbarissue](https://github.com/FriendsOfREDAXO/tricks/issues/39) möchte @cukabeka gerne wieder ein [Cheatsheet](http://webbude.com/files/ooredaxo_41.pdf) wie das von @tbaddade haben. Es ist sehr kompakt, übersichtlich und enthält alles, was man für einfache Modulausgaben benötigt. Wäre es nicht sinnvoll, @skerbis' Stub in "Cheatsheet Artikel" umzubenennen und eine Formatierung zu finden, die eine kompakte Darstellung analog zum oben verlinkten PDF Cheatsheet ermöglicht? Weiterhin könnte es dann noch "Cheatsheet Redaxo Vars"/ "Cheatsheet Slice"/ "Cheatsheet Kategorie"/ "Cheatsheet Media" etc. geben.

@madiko oder @cukabeka  zb könnten dann diese Cheatsheets füllen und hätten im PDF Cheatsheet eine Vorlage für Inhalt und Struktur. Ich bin nämlich wie @tbaddade keine besonderer Fan der fantasievoll benannten und für die Doku vollkommen überflüssigen Variablen zum Zwischenspeichern...

**Comment by skerbis** [comment]
Ich stimme dem voll zu. @IngoWinter Aktuell gibt es keinen besseren Platz. Auch die Mini-Beispiele sind ebenso führ die Erfahrenen zu einfach. Für Anfänger jedoch Tricks. Ich halte nichts von Cheatsheets, will da auch nichts beisteuern. Der Artikel hier kann sicher noch gestrafft werden.

**Comment by alexplusde** [comment]
Eine Übersicht an Methoden und Beispielen könnte man z.B. so machen, wie ich das bei YRewrite vorgeschlagen habe:
https://github.com/yakamara/redaxo_yrewrite/issues/192#issuecomment-354596921 

(ist noch nicht ausgereift, ich warte auch hier erstmal auf das Doku-Plugin)

**Comment by IngoWinter** [comment]
So vielleicht https://github.com/FriendsOfREDAXO/tricks/pull/55

**Comment by skerbis** [comment]
Ist gemerged. Wird demnächst im Inhaltverzeichnis als in Bearbeitung , Hilfe erwünscht markiert
