### ISSUE TITLE
Die Tricks werden langsam unübersichtlich / Website anpassen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/tricks#58]
Alternativen? Vorschläge zum Aufbau?

**Comment by alexplusde** [comment]
Noch geht's, wenn man sich https://friendsofredaxo.github.io/tricks/ anschaut.

Zwei Ideen:
* Minibeispiele auf eine Seite eindampfen. 
* Tricks zu Addons, die eine Doku haben (bspw. MForm, YForm) oder eine bekommen (bspw. YRewrite), dorthin bewegen.

**Comment by IngoWinter** [comment]
den link von @alexplusde kannte ich noch gar nicht. welche möglichkeiten hat man denn da, per css und javascript zu arbeiten?

**Comment by skerbis** [comment]
Ist nur eine von Github generierte Seite. Nicht veränderbar

**Comment by IngoWinter** [comment]
da ist doch ein theme installiert. und über ein theme müsste man doch css und javascript laden können...

**Comment by alexplusde** [comment]
https://help.github.com/articles/customizing-css-and-html-in-your-jekyll-theme/

**Comment by schuer** [comment]
Die GitHub Pages sind sehr flexibel. Im Frontend (HTML, CSS, JS) sowieso, aber auch im Umgang mit den Repo-Daten geht einiges — wenn auch nicht so viel wie etwa in einer PHP-Umgebung. Am Ende bleibt es eine statische Seite. Die gleiche Technik nutzt übrigens auch unsere Community-Map und die FOR-Website.

Weitere Vorschläge, um die Tricks übersichtlicher und zugänglicher zu gestalten:

* Mit [Collections](https://jekyllrb.com/docs/collections/) arbeiten, um den Index automatisch generieren lassen zu können.
* Syntaxhighlighting einbauen
* Sprungmarker einbauen
* Suchfunktion einbauen

**Comment by skerbis** [comment]
Darf gerne jemand übernehmen. Die hier gezeigte Seite hat aber kein Repo - oder doch?

**Comment by schuer** [comment]
Ich setze gerne mal die Tricks-Website auf, allerdings ist zu bedenken, dass dafür das Repo etwas umgebaut werden muss, so dass es danach nicht mehr ganz so gut über die GitHub-Weboberfläche zugänglich ist:

* Im Root kommen ein paar Ordner und Dateien hinzu für Jekyll. Das macht es etwas unübersichtlicher, und Nutzer könnten sich wundern, wofür all diese Files notwendig sind.
* Die Artikeln wandern in ein Unterverzeichnis mit Unterstrich am Anfang, z. B. `_docs`. Alle Tricks-Inhalte befinden sich danach also in diesem Ordner.
* Die Artikel bekommen einen Metadatenblock (etwa 5-7 Zeilen) an den Anfang der Datei. Wenn man die GitHub-Weboberfläche verwendet, wird man diese Metadaten immer sehen.

Die Tricks werden auf der GitHub-Weboberfläche also an Übersichtlichkeit verlieren, dafür wird die neue Website sehr schnieke und aufgeräumt:

* Der Index wird automatisch erstellt
* Wir können individuell formatieren und stylen, also auch eigenes CSS und JS einbringen
* Features wie Syntaxhighlighting und Sprungmarker
* Wir können eine Suchfunktion einbauen, sobald verfügbar (ab Jekyll 3.7, aktuell läuft bei GitHub noch 3.6)

**Fragen in die Runde also: Ist das in eurem Sinne, dass wir die Ansicht der Tricks von der GitHub-Oberfläche hinüber zur Website verlagern?**

**Comment by IngoWinter** [comment]
+1 für schnieke Tricks Website

**Comment by dergel** [comment]
und in die redaxo.org integrieren ? oder ist das zu umständlich ? Wir hatten ja mal die Idee Codeschnipsel/Tricks als Suche innerhalb von redaxo.org einzubauen. Eventuell kann man auch eine externe Seite machen und nur die Suche mit auf redaxo.org aufnehmen.

**Comment by dtpop** [comment]
Es gab immer wieder mal die Idee die Tricks in die Doku zu integrieren. Ich halte sie allerdings unverzichtbar separat zu halten, da einiges Core- und AddOn-übergreifend ist und so den unbedarften Benutzer animiert auch mal ein unbekanntes AddOn in seine Architektur aufzunehmen. Durchsuchbar aus redaxo.org wäre fast so etwas wie must have. Gerade die nicht-Experten tun sich schwer viele verschiedene Quellen abzusuchen.

**Comment by alexplusde** [comment]
+1 für die Integration in die Hauptwebsite und eine Suchfunktion für Doku und Tricks.

**Comment by schuer** [comment]
Integration in redaxo.org und Implementierung einer Suche müsste dann jemand übernehmen. Ich würde nur die GH-Pages-Lösung umsetzen, falls diese gewollt würde.

**Comment by staabm** [comment]
integration in redaxo.org würde ich nicht machen, da wir viel zu wenig leute haben die zeit haben dort was einzubauen und zu pflegen.

wenn es standalone auf github bleibt ist der user-kreis der daran arbeiten kann viel größer

**Comment by skerbis** [comment]
Das haben wir schon oft diskutiert. Die besagte Stippet-Sammlung wäre mir lieber auf REDAXO.org. Dann werden auch die Tricks schlanker. Die Tricks sollten auch eher Anwendungsfälle lösen als Modul X (z.B. die Minibeispiele) liefern.

**Comment by dergel** [comment]
lasst uns das weiterüberlegen.. Die Argumente gegen die Webseite sind ja eher wegen Aufwand und nicht, weil es nicht dort bessser aufgehoben wäre. Was bräuchten wir für Felder und welche Art von Suche.

Titel, Beschreibung, Code, Kategorie/Bereich ?
Nur Volltextsuche mit Highlighting ?

**Comment by alexplusde** [comment]
Vielleicht hat @tyrant88 ja eine zweckdienliche Idee zur Umsetzung, schließlich führt er das Repo zu `search_it`.

**Comment by tyrant88** [comment]
Search it nutzt zwar Sockets zum Indexieren, aber eine "Spider" ist es noch nicht. Also bei externen Inhalten hilft es nicht.

**Comment by alexplusde** [comment]
Die Diskussion, wie Inhalte von hier auf redaxo.org kommen können, hatten wir eigentlich schon mal ergebnislos geführt: https://github.com/FriendsOfREDAXO/friendsofredaxo.github.io/issues/2

**Comment by schuer** [comment]
@alexplusde In der verlinkten Diskussion ging es vor allem darum, wie wir mit FOR unsere AddOns veröffentlichen können, ohne dass es ein manueller Prozess ist und alle Beteiligten die Zugangsdaten benötigen. Und ergebnislos war die Diskussion gar nicht mal, sondern der Plan war am Ende, dass _irgendwann_ eine automatische Veröffentlichung aus GitHub heraus implementiert werden soll. Allerdings ist das bisher noch nicht geschehen, und wir veröffentlichen weiterhin manuell mittels Zugangsdaten.

**Comment by skerbis** [comment]
Insgesamt bin ich mit der Auffindbarkeit der Informationen in den Tricks (aber auch der Doku) sehr unzufrieden. Die Mehrheit der Tricks sind Snippets und kleine Manuals. Diese brauchen eine Struktur (Kategorisierung)  und ggf. Tagging. Ich weiß nicht ob sich dies in GitHub wirklich lösen lässt. Ggf. eine REDAXO Website, die sich die Daten wie bei den Dokus auf REDAXO.org zieht. Eigentlich ist es ein wenig peinlich, dass wir in REDAXO auf sowas wie GitHub-Pages zurückgreifen.

**Comment by staabm** [comment]
> Eigentlich ist es ein wenig peinlich, dass wir in REDAXO auf sowas wie GitHub-Pages zurückgreifen.

die ganz großen wie symfony etc. machen das auch so. github hat den ultimativen vorteil dass eben jeder daran pflegen kann und man keinen speziellen account dafür brauch.

**Comment by skerbis** [comment]
Hier meinte ich eher die Ausgabe der Seiten @staabm

**Comment by schuer** [comment]
Für GitHub Pages kann man auch eigene Subdomains verwenden, z. B. docs.redaxo.org oder tricks.redaxo.org.

**Comment by alexplusde** [comment]
Dann könnte man bspw. `snippets.redaxo.org` nehmen und `tricks.redaxo.org` - womit das ursprüngliche Thema angegangen würde - die Tricks übersichtlicher machen und so gliedern.

**Comment by schuer** [comment]
Was sind denn diese Snippets eigentlich und warum sind sie nicht Teil der Tricks? Und warum soll das alles so verteilt auf viele Instanzen sein — Doku, Tricks, Snippets —, statt gemeinsam unter einem Dach? Die Kritik von Nutzern ist ja oftmals, dass REDAXO-Hilfe zu breit verteilt ist und dadurch schlecht gefunden wird. Sollten wir hier nicht lieber entgegenwirken, indem wir versuchen, mehr zu bündeln?

**Comment by schuer** [comment]
Okay, dann können wir nach der ganzen Diskussion schonmal festhalten, dass die Doku besser auf redaxo.org bleiben sollte und langfristig aber unbedingt mal eine Suche erhalten sollte, richtig?

Dann bleiben noch Tricks und Snippets, danke für die Info @skerbis! Ich persönlich sehe die Tricks eher als **GitHub Pages** — erreichbar unter der von GitHub angebotenen Domain https://friendsofredaxo.github.io/tricks/ oder über eine REDAXO-Subdomain wie z. B. https://tricks.redaxo.org —, und ich würde Tricks und Snippets unbedingt gemeinsam anbieten, nicht zwei Projekte draus machen. Die Tricks wären damit eine Anlaufstelle für alles, was nicht in die Doku passt, also AddOn-bezogene Tutorials, Codebeispiele oder sonstige Hilfen.

Ich würde die Tricks nicht in redaxo.org integrieren, weil die Integration und Pflege sonst von den Core-Leuten übernommen werden muss, während wir an GitHub Pages alle gemeinsam arbeiten könnten. Zudem ist das Hosting bei GitHub robuster, schneller und weniger aufwendig. Es läuft einfach, niemand muss sich drum kümmern.

Bezüglich **Suche und Tagging**: GitHub Pages sind vollständig statisch, werden also aus den Repo-Daten heraus einmalig generiert und haben keine Möglichkeit von serverseitiger Datenverarbeitung, wie man sie etwa bei einer Suche bräuchte. Dennoch ist eine Suche mit GH Pages möglich, und sogar sehr komfortabel: Die Indizierung übernimmt ein externer Service ([algolia.com](https://www.algolia.com), dauerhaft kostenlos für OSS-Projekte), und die Integration auf der Seite ist dann mittels JS und API. Bei [Jekyll](https://jekyllrb.com) oder [symfony](https://symfony.com/doc/current/index.html) seht ihr, wie das funktioniert: Einfach irgendwas ins Suchfeld tippen, dann kommt ein Flyout mit Vorschlägen.
Und auch Tagging ist möglich, indem man einfach eine Tag-Übersichtsseite generiert, die auf die einzelnen Artikel verlinkt. Beispielhaft hier zu sehen: http://codinfox.github.io/blog/tags/

**Comment by schuer** [comment]
Kleines Update: Die Suche für GH Pages steht längst zur Verfügung. Ich dachte, wir müssten aufs nächste Release warten, aber das war Bullshit. Die Suche, weil extern, kann schon jetzt eingesetzt werden. ✅

**Comment by alexplusde** [comment]
Wer kann sich um die Integration kümmern?

**Comment by IngoWinter** [comment]
@schuer hat schon vor 5 tagen angeboten, sich drum zu kümmern...

**Comment by schuer** [comment]
(Aber nur GH Pages. Falls Integration in redaxo.org gewünscht wird, also auf PHP-Basis, müsste das jemand anderes machen.)

**Comment by IngoWinter** [comment]
ach, wenn das unbedingt auf redaxo.org soll (wobei mir der nicht klar ist, welchen vorteil das bringen soll), kann @gharlan ja einfach nen iframe reinnageln und gut ist.

**Comment by skerbis** [comment]
Hauptsache es wird schnieke. @schuer lass rocken! Suche, Tagging - cool. Dann wird das was.

**Comment by dergel** [comment]
gerne extern - weil es realistischerweise zeitlich auf redaxo.org nicht klappen wird und veränderungen erst recht dauern. Ich würde dennoch die Tricks auffällig auf der r.org seite verlinken... Wenn die Seite so cool wird wie die community seite - top !!

**Comment by schuer** [comment]
GitHub hat inzwischen Jekyll 3.7 am Start (siehe https://pages.github.com/versions/), und ich hatte irgendwie gedacht, dass sie in dem Zusammenhang auch [jekyll-algolia](https://community.algolia.com/jekyll-algolia/) als Plugin hinzufügen, was es einfacher machen würde, die Inhalte der Seite bei Änderungen an die [Algolia-Docsearch](https://community.algolia.com/docsearch/) zu übergeben, so dass der Index dort immer schnell auf dem aktuellen Stand ist.
Aber nein, das Plugin haben sie nicht hinzugefügt.

Macht aber nichts, denn man kann zum Push der Inhalte Travis CI verwenden, so wie hier beschrieben: https://community.algolia.com/jekyll-algolia/github-pages.html

Und auch ohne Travis könnte Agolia problemlos angebunden werden, verfügt es doch über einen Crawler. Der ist naturgemäß langsamer bei Änderungen, als ein Push es wäre, aber sollte in unserem Fall auch gut funktionieren.

**Comment by schuer** [comment]
Suche muss noch integriert werden (#81), aber ansonsten können wir jetzt sicherlich schließen.
