### ISSUE TITLE
YForm + Select + E-Mail-Template + Sprog

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/tricks#6]
Memo für mich aus Slack via @tbaddade 

```
ich habs grad heute so gelöst aber halt mit radios
select|key|Label|{{ option.1 }}=1,{{ option.2 }}=2

im ytemplate dann
<?= sprogcard('option.REX_YFORM_DATA[field=key]') ?>


```

**Comment by alexplusde** [comment]
Generell: Mehrsprachigkeit in YForm-Feldern für Labels (Frontend) und Labels/Values (Backend).

**Comment by alexplusde** [comment]
Müsste jetzt an Choice angepasst werden.

**Comment by eaCe** [comment]
funktioniert auch mit value/label

`
                    $yform->setValueField('choice', array(
                        'name' => 'profile',
                        'label' => '',
                        'choices' => sprogcard('terms_profile_select')
                    ));
`

`Label=value,Label=value`

**Comment by alexplusde** [comment]
Gehört eher in die Doku von choice, wie man in E-Mail-Templates mit PHP umgeht als gutes Beispiel.
