### ISSUE TITLE
Notiz: Ändern des Startartikels on the fly

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/tricks#63]
```php
// in die Boot deines AddOns setzen

$structureAddon = rex_addon::get('structure');
// $id durch einen Config-Wert oder durch Abfragen ersetzen
 $structureAddon->setProperty('start_article_id', $id);
 
 if (rex_request('article_id', 'int') == 0) {
    $structureAddon ->setProperty('article_id', rex_article::getSiteStartArticleId());
} else {
    $article_id = rex_request('article_id', 'int');
    $article_id = rex_article::get($article_id) ? $article_id : rex_article::getNotfoundArticleId();
     $structureAddon ->setProperty('article_id', $article_id);
}


```

**Comment by skerbis** [comment]
Erlaubt es den Startartikel abseits der Systemkonfiguration zu ändern. z.B. für eine saisonale Dartstellung, Aufruf bei hoher Last, Hinweis zu Wartungsarbeiten etc.

**Comment by alexplusde** [comment]
Dieser Aufruf erfolgt ungeschützt, wenn ich das richtig sehe. Es sollte zumindest ein Passwort/Schlüssel/Hash nötig sein, damit nicht von außen einfach ein `?article_id=7` angehängt wird.

Es fehlt ein `i` bei `if`.

**Comment by skerbis** [comment]
ist tatsächlich der Originalcode aus dem Structure-AddOn
