### ISSUE TITLE
Tricks AddOn-Entwicklung: Wie stelle ich dem Redakteur mehrere Editoren zur Auswahl?

### ISSUE THREAD

**Issue by madiko** [FriendsOfREDAXO/tricks#68]
Anleitung, was man dabei als Entwickler beachten muss und wenn möglich code-snippets.

Merker: In die Doku zu den einzelnen Editoren als FAQ aufnehmen.
[Doku markitUp!-Editor > dort habe ich es bereits vorbereitet]

**Comment by alexplusde** [comment]
Verstehe die Anforderung nicht.

**Comment by skerbis** [comment]
Ist mir nun auch nicht ganz klar? Du möchtest dem Redakteur die Auswahl des Editors überlassen? Bedenke ein Switch zwischen markdown -> html -> textile ist so gut wie unmöglich

**Comment by cukabeka** [comment]
Ich vermute, es geht eher um Redactor vs CKE5 oder evtl sogar von Markitup, falls man in einem Textarea plötzlich statt textile doch HTML verwenden möchte.

**Comment by alexplusde** [comment]
Will man das? Steht doch was vollkommen unterschiedliches in der Datenbank.

**Comment by madiko** [comment]
Hallo zusammen,

stimmt, ist in dieser verkürzten Version etwas kryptisch geraten. 

Es ging darum, den AddOn-Entwicklern eine Anleitung anzubieten, wie sie es ermöglichen, mehrere der verschiedenen Editoren für die Nutzer des AddOns anzubieten. Hier hat ja doch jeder seine Vorlieben. Gleichzeitig verstand ich die Idee so, dass wir damit auch eine gewisse Konsistenz und Stabilität in die REX-AddOns (Qualitätssicherung) einbauen, da die Entwickler dann auf bewährte Vorgehensweisen / Code-Snippets zurückgreifen können und wir diese dann wieder gebündelt weiterentwickeln (Skalierung nutzen).

Entstanden war das Thema im Zusammenhang mit der Weiterentwicklung des "d2u_news"-AddOns von Tobias. Er hat für sich jetzt auch eine individuelle Lösung gefunden und wäre vielleicht bereit, seine Erfahrungen mit einzubringen? Siehe https://github.com/TobiasKrais/d2u_news/issues/1

Viele Grüße,
Franziska

ping @TobiasKrais

**Comment by skerbis** [comment]
Was Tobias gemacht hat ist sicher sehr pflegeintesiv, da er sein AddOn in Abhängigkeit zu den Editoren bringt. Der Ansatz der z.B. in sked oder in MultiGlossar verfolgt wird ist ggf. die bessere Lösung. Die Editoren können einfach durch entsprechende CSS- oder JSON-Definitionen eingebunden werden. So kann jeder den Editor verwenden, den er mag und das AddOn den Wünschen entsprechend leicht konfigurieren.

**Comment by TobiasKrais** [comment]
Wie @skerbis schon geschrieben hat ist meine Lösung vergleichsweise pflegeintensiv. Das Problem beim Wechsel der Editoren ist, dass gegenseitig inkompatible Formate in der DB gespeichert werden können. Heißt: wenn einmal in der DB MarkITUp Text gespeichert wurde, und ich danach meinen Editor auf TinyMCE umstelle, ist die Ausgabe hinüber, da die Ausgabe dann nicht mehr per MarkITUp aufbereitet wird.

Dennoch hat meine Lösung einen Vorteil gegenüber der von Sked: meine Lösung ist für den Nutzer komfortabler. Sked kann nur die Klasse des Eingabefeldes anpassen. Angenommen ich gebe die Klasse des MarkITUpEditors an, wird dann auch der auszugebende Text per MarkITUp aufbereitet? Sieht für mich auf den ersten Blick nicht so aus. Es können vermutlich nur WYSIWYG Editoren per CSS-Klasse eingebunden werden die fertiges HTML in die DB schreiben.

Den Ansatz hier von Sked finde ich sehr pfiffig - und einfach zu handeln. Tolle Idee!

**Comment by skerbis** [comment]
@TobiasKrais @madiko  Hi. Bei Sked, yform und Glossar ist man für die Ausgabe ja selbst verantwortlich, daher kann jeder Editor in dieser Form verwendet werden. Es ist halt je AddOn abzuwägen, was sinnvoller ist. Eine allgemeine Empfehlung kann man nicht abgeben.  Evtl.  könnte man den Ausgabecode mit über das json übergeben?

**Comment by olien** [comment]
Ich würde Abfragen welcher Editor installiert ist und darauf reagieren. Sind mehrer installiert wird halt irgendeiner benutzt...

**Comment by skerbis** [comment]
Da es kein Standard gibt, wie in REDAXO was eingebunden ist und sich Editoren nicht "anmelden", sehe ich hier aktuell keine Möglichkeit einen allgemein gültigen Weg zu finden.

**Comment by skerbis** [comment]
Ich mache hier erstmal dicht, da es keinen allgemeinen Weg aktuell gibt. Kann gerne wieder geöffnet werden, wenn sich was neues ergibt.
