### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/tricks#7]
Gerade vom @staabm geschickt bekommen und ich denke auch für REDAXO ein guter Tip wenn man mal größere Seiten mit mehr Cachefiles hat (was gaanz sicher oft existiert)...

Performance Infos 

http://symfony.com/doc/current/performance.html#optimizing-all-the-files-used-by-symfony

**Comment by skerbis** [comment]
Siehe hierzu auch: https://www.scalingphpbook.com/blog/2014/02/14/best-zend-opcache-settings.html

**Comment by alexplusde** [comment]
In welcher Dimension reden wir denn da von größeren Seiten mit mehr Cachefiles? Ab wann macht sich das bemerkbar?

Wäre auch super, wenn in dem Issue ein paar Erläuterungen / Linktipps landen, mit denen Einsteiger eine Performance-Messung durchführen können.

**Comment by staabm** [comment]
Im Link von @skerbis  ist schön beschrieben wie man es berechnen kann. Es ist immer von Anwendungs/Seitengröße abhängig daher gibts keine "generelle Empfehlung".

Beispiel: `opcache.max_accelerated_files` hat einen php-ini default von 2.000. Die symfony Empfehlung ist 20.000. In den Anwendungen für unsere Company brauchen wir einen Wert von 50.000 (da viele files).

**Comment by dergel** [comment]
werden die redaxo cache files in diesem fall als php Files betrachtet ? weil dann sind wir in sehr schnell in diesem 2000 er Bereich

**Comment by staabm** [comment]
@dergel hängt von der Dateiendung ab. Den aktuell benötigten Wert kann man z.b. mit `find . -type f -print | grep php | wc -l` rausfinden

**Comment by dergel** [comment]
d.h. wenn wir die Dateiendung noch anpassen, im moment ist .content und .article und da noch ein .php dazusetzen, würde der opcache erst greifen.. D.h. im Moment greift er bei REDAXO an diesen Stellen gar nicht, oder verstehe ich das falsch ?

**Comment by gharlan** [comment]
So wird es wohl sein. Und leider haben wir bei den ganzen anderen Cache-Dateien aufs ganz 'falsche Pferd' gesetzt, dort nutzen wir ja JSON.
Da könnte man auch mal schauen, ob wir das (an einigen Stellen) auch nochmal ganz ändern, und für Opcache optimierte PHP-Dateien nutzen.

**Comment by staabm** [comment]
Generell muss man erstmal messen ob es aus Perf. sicht einen unterschied macht wenn die cache dateien durch den Opcache laufen würden.

**Comment by dergel** [comment]
bei den .content Cache Dateien bin ich mir ziemlich sicher .. Genau dafür ist es, nach meinen Vorstellungen, ja gemacht.. Aber stimmt - sollte man einfach mal durchmessen und dann schauen.

**Comment by staabm** [comment]
weiterer Artikel zum Thema https://tideways.io/profiler/blog/fine-tune-your-opcache-configuration-to-avoid-caching-suprises

**Comment by alexplusde** [comment]
@staabm dein Vortrag zur Performance-Messung mit Blackfire sollte hier nicht unerwähnt bleiben.

Link zum Dienst: https://blackfire.io/

**Comment by alexplusde** [comment]
Wäre das was für R5.7?

**Comment by staabm** [comment]
Welcher der genannten punkte der diskussion meinst du genau?

Was sich mittlerweile auch getan hat bzgl dieser settings: blackfire zeigt einem an wenn man die genannten settings „nicht gut“ eingestellt hat, siehe https://blog.blackfire.io/cache-information.html

**Comment by staabm** [comment]
Bzgl eines tricks kapitels: ggf würde es reichen ein kleinen artikel zu haben der die genannten links aus der diskussion sammelt, sodass man von einem zentralen punkt aus infos für perf optimierungen bekommt ohne alle inhalte von den externen seiten zu duplizieren

**Comment by skerbis** [comment]
@staabm hast du Lust? Vielleicht mit ein paar kleinen Hinweisen zur REDAXO selbst war goes und no- goes sein sollten

**Comment by staabm** [comment]
Ich würde meine zeit lieber im weiterentwickeln/fixen von redaxo core dingen machen.

Ich denke die linksammlung könnte (basierend auf dieser diskussion) fast jeder machen (vllt mal im slack fragen). Einzelne redaxo spezielle hinweise kann dann nemand beisteuern der das system auch produktiv regelmäßig verwendet - das trifft auch mihc ja auch nicht zu :-]

**Comment by alexplusde** [comment]
Ich hab' z.B. keine Ahnung, wie man Blackfire nutzt, also wie der Weg ist von "ich habe ein REDAXO" hin zu "Ich kann in Blackfire etwas sehen".

@staabm ich meinte jetzt, die Dateiendungen und ggf. auch Dateitypen so anzupassen, dass opcache greift.

**Comment by staabm** [comment]
Bzgl dateiendungen: vom gefühl her würde ich sagen dass es aktuell andere dinge gibt die die performance stärker beeinflussen. Wenn jemand das gegenteil “ beweisen“ kann man da natürlich genauer reinschauen.

Das thema im speziellen sollte dann aber ein issue im redaxo core werden statt hier das eigentliche thema zu verwäassern

**Comment by skerbis** [comment]
Ich mache hier zu ... Diskussionen zu diesem Thema gerne in https://github.com/orgs/FriendsOfREDAXO/discussions
