### ISSUE TITLE
Zu: geschützte Dateien mit YCom

### ISSUE THREAD

**Issue by WolfgangBusch** [FriendsOfREDAXO/tricks#70]
Wie groß dürfen Mediadateien sein, damit ich bei
        ...
        $managed_media = new rex_managed_media(rex_path::media($filename));
        (new rex_media_manager($managed_media))->sendMedia();
        ...
keinen Speicherüberlauf bekomme?

**Comment by skerbis** [comment]
@gharlan - Hast du Infos dazu?

**Comment by skerbis** [comment]
Ist wohl abhängig vom Server
