### ISSUE TITLE
Fehlerbehebung

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/tricks#71]
Fehler, die in SLACK immer wieder gemeldet werden, könnten mit deren Lösung in den Tricks aufgenommen werden, ungefähr so:

Ich habe leider gerade nicht alles zur Hand. Was ist die grundsätzliche Meinung?

## SVGs werden nicht ausgegeben 

Lösung:
Grund ist eine Änderung der .htaccess in REDAXO 5.5. Hier im Zweifel die betroffene Zeile auskommentieren.

## Core kann nicht aktualisiert werden

Problem:
![image](https://user-images.githubusercontent.com/3855487/40245257-636dc50a-5ac5-11e8-9130-a3b83f03d999.png)

Lösung:
Diesen Befehl in der Datenbank ausführen
```
ALTER TABLE rex_config
DROP PRIMARY KEY,
ADD COLUMN `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY (`id`),
ADD UNIQUE KEY `unique_key` (`namespace`,`key`);
```

## YForm kann nicht aktualisiert werden // FOREIGN KEY

Lösung:
Den betroffenen Fremdschlüssel in der Datenbank entfernen.

**Comment by skerbis** [comment]
@alexplusde noch akut?

**Comment by alexplusde** [comment]
Kann immer noch vorkommen, da sich das auf ältere Versionen von Core, YRewrite und YForm bezieht

**Comment by alexplusde** [comment]
Es sollte diese Rubrik geben, aber da ich sowieso der einzige bin, der sie sammelt...
