### ISSUE TITLE
Frage zu NGINX-Konfiguration für YRewrite

### ISSUE THREAD

**Issue by fietstouring** [FriendsOfREDAXO/tricks#74]
Ich verwende Plesk: Habe den Proxy Mode - also Apache - ausgeschalten und die Konfiguration in das Feld "Additional Headers" eingetragen. Leider kommt eine Fehlermeldung: 

> specified header is invalid "#}" 

das kommt bei allen Anweisungen mit geschwungenen Klammern.
ausserdem hab ich gesehen, dass die # REWRITE RULE FOR JS/CSS VERSIONING
glaube ich da nicht enhalten ist, oder?

Vielleicht weiß jemand was dazu...

**Comment by skerbis** [comment]
Bitte ein entsprechendes Issue bei YRewrite anlegen
