### ISSUE TITLE
Möglichkeiten, Website im dev/Entwurfs-Stadium schützen.

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/tricks#8]
Wie schützt ihr Websites, die noch nicht online sein sollen, aber für den Kunden erreichbar / sichtbar? Via htpasswd? Gibt's da evtl. ein Addon/Klasse/Codeschnippsel, mit dem das bei euch automatisch im Projekt landet?

**Comment by olien** [comment]
Hm. Früher mit dem XOutPutFilter und Aktuell mit out5 :-)

**Comment by alexplusde** [comment]
Wie sah denn ein Filter dafür aus?

**Comment by olien** [comment]
Recht einfach:


```
if (!rex::isBackend()) {
	if ($this->getConfig('status') != 'deaktiviert') {
		$session = rex_backend_login::hasSession();
		if (!$session) {
			header('Location: ' . $this->getConfig('url'));
			exit;
  		}
  	}
}

**Comment by tyrant88** [comment]
Wichtig ist nur der "noindex, nofollow" Meta tag. Du musst dich nur vor Google "schützen".

**Comment by schuer** [comment]
Wir machen das in der Tat mittels htpasswd. Dann ist es sicher in jeglicher Hinsicht (Google), und man muss keine zusätzliche Funktionalität integrieren.

**Comment by staabm** [comment]
mit php alleine kann man auch mit 5 zeilen code ein einfachen http basic auth realisieren:
http://php.net/manual/de/features.http-auth.php

**Comment by alexplusde** [comment]
Ich glaube, dazu mache ich mal in der Doku einen Q&A-Abschnitt auf.

Welches Tool nehmt ihr für htpasswd @schuer?

**Comment by schuer** [comment]
Das wird eigentlich fast immer direkt im Adminbereich des Servers/Hosters konfiguriert.

**Comment by staabm** [comment]
htpasswd hat den nachteil dass es nur mit apache geht und teilweise je nach version auch unterschiedlich notiert werden muss. Ab apache 2.4 beachtet der apache auch von haus aus keine .htaccess dateien mehr.

eine php lösung wäre server unabh. und mit wenig aufwand machtbar. (s.o.)

**Comment by tyrant88** [comment]
Und wo kommen dann die Passwörter ("unaufwändig") her?

**Comment by staabm** [comment]
> Und wo kommen dann die Passwörter ("unaufwändig") her?

z.b. ein backend user oder irgendwo ein fest hinterlegter wert (an der gleichen stelle wo man dann den mechanismus aktiviert/deaktiviert)

**Comment by skerbis** [comment]
Ich frage im Template schon mal eine Session-Variable ab, deren Wert der Kunde über eine GET-Variable setzt. http://xyz.tld?test=XYZ

**Comment by alexplusde** [comment]
@schuer ich habe die Möglichkeit bei ein paar Hostern nicht. Und außerdem die Sorge, dass dabei die Redaxo-htaccess-Datei angefasst wird.

@skerbis @staabm @tyrant88 @olien ich habe das hier mal zusammengestellt, evtl. findet es ja den Weg in die Doku: 
https://github.com/redaxo/docs/issues/6

/cc @polarpixel

**Comment by schuer** [comment]
Sehr fein, danke @alexplusde!
