### ISSUE TITLE
Website: Mitwirkende wird nicht automatisch aktualisiert

### ISSUE THREAD

**Issue by bloep** [FriendsOfREDAXO/tricks#86]
Nachdem ich heute meinen ersten Artikel in dem Repo erstellt habe, ist mir aufgefallen, dass die Liste der Mitwirkenden am Ende jeder Seite nicht automatisch aktualisiert wird.

Ich meine die sollte doch eigentlich automatisch geupdated werden oder?

**Comment by schuer** [comment]
GitHub updatet die Daten nicht Live, sondern im Intervall, meine ich. Nach jeder Änderung dieses Repos wird allerdings innerhalb einer Minute die Website aktualisiert, und dann sind die aktualisierten Daten von GitHub noch nicht verfügbar, so dass die Website noch den alten Stand (bzgl. Mitwirkender) anzeigt. Erst mit dem nächsten Website-Update kommen die Daten auf die Website.

Wir könnten Travis einmal am Tag bauen lassen, so wie wir es auch auf der [FOR-Website](https://friendsofredaxo.github.io) machen, um zumindest täglich einen aktuellen Stand der Sterne zu holen.

**Comment by schuer** [comment]
Ich habe übrigens eben einen Test-Commit gemacht, um die Website bauen zu lassen, und damit bist du jetzt auch unter den Mitwirkenden zu sehen.
