### ISSUE TITLE
Globale Inhalte - einmal machen, überall darstellen

### ISSUE THREAD

**Issue by abra100pro** [FriendsOfREDAXO/tricks#88]
Wenn ein Inhalt auf mehreren Seiten dargestellt ("gespiegelt"), aber nur an einem Ort gepflegt werden soll. Die Beschreibung ist exemplarisch - man kann Kategorieren und Artikel und alles auch anders benennen:

1. Ich erstelle eine Kategorie "Global"
2. Darin lege ich einen oder mehrere Artikel, die NUR den Inhalt haben, den ich spiegeln möchte
3. Dann erstelle ich ein Modul mit folgendem Input und Output (siehe unten)
4. dieses Modul integriere ich auf den Seiten, die den globalen Inhalt haben sollen und wähle dort im Modul den gewünschten globalen Artikel. 

Funktioniert mit Inhalt, Styles, Funktionen, etc.

Input:

`Ein beliebiger Artikel kann hiermit auf dieser Seite gespiegelt werden und muss nur einmal gepflegt werden. Der Artikel sollte sich immer unter Kategorie "Global" > Kategorie "Globale Blöcke" befinden.<br /><br />

<div class="row">
<div class="col-sm-12">
Artikel auswählen:<br /> 

    REX_LINK[id=1 widget=1]
</div>
</div>`

Output:

`<?php
$article_id = REX_LINK[id=1];
$clang_id   = 1;
$art = new rex_article_content($article_id, $clang_id);
if (null !== $art) {
    echo $art->getArticle();
}
?>
`

Danke an Adrian Kühnis und RexDude für Hilfe und Tips.

**Comment by alexplusde** [comment]
Ich nehm dafür das Globale Einstellungen Addon oder eine YForm-Tabelle. Worin liegt der Vorteil in dieser Lösung?

Man sollte beachten, dass hier ggf. Artikel im Google-Index landen, die da nicht sein sollten.

**Comment by abra100pro** [comment]
Tönt auch gut! :-) Ich kennen halt nur "meine" Lösung. Wenn Du Zeit und Lust hast, deine kurz zu beschreiben, dann würde ich sie gern mal probieren. Denn das mit Google hat was...

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/tricks/blob/master/_docs/module/minibeispiel_artikel_einbinden.md könnte man hier ergänzen

**Comment by alexplusde** [comment]
@abra100pro

Probier das Addon “globale Einstellungen“ einfach mal aus, dann siehst du, wie man es einsetzen kann. Ist gut erklärt. Gibt's im Installer.

**Comment by skerbis** [comment]
@alexplusde der Vorteil bei dieser Lösung ist mehr oder weniger die Pflegbarkeit durch den Redakteur

**Comment by alexplusde** [comment]
@skerbis

Guter Einwand, eignet sich für eine Gegenüberstellung

**Comment by skerbis** [comment]
Möchte das nicht weiter ausführen. In diesem Beispiel handelt es sich um eine simple Artikeleinbindung, die bereits erklärt ist. @abra100pro gerne kannst du was zu meinem Tipp ergänzen. Würde mich freuen. 
Ich schließe das Thema.

**Comment by skerbis** [comment]
Hier noch neu als Ergänzung: 
https://friendsofredaxo.github.io/tricks/module/slice_einbinden
