### ISSUE TITLE
Variable modulübergreifend speichern

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/tricks#89]
Slack:
"Moin. Kurze Frage: Ich definiere in einem Template "$test = 1" und möchte dann in einem Modul auf $test zugreifen. Leider klappt die Übergabe nicht, ich bekomme keine Ausgabe. In Rex-4 ging das aber, in Rex5 scheinbar nicht mehr!? Oder hab ich irgendwo einen unentdeckten Fehler im Code?"

@staabm 
man sollte nicht darauf vertrauen dass lokale variablen von einem context in einen anderen verfügbar werden. das dies früher ging war technisch bedingt und kein bewusstest feature.
am besten mit rex::setProperty() arbeiten, dann siehst du explizit was wie/warum passiert

m.E. ein Fall für die Tricks

**Comment by skerbis** [comment]
nein, aber evtl. hier ergänzend erklären

**Comment by aeberhard** [comment]
Für diesen Zweck habe ich das Addon properties gebastelt
https://github.com/FriendsOfREDAXO/properties

**Comment by skerbis** [comment]
Es gibt zig Wege in REDAXO ... das ist ja das tolle

**Comment by skerbis** [comment]
https://redaxo.org/doku/master/eigenschaften
