### ISSUE TITLE
Grundlagen Online-Redaktion Einleitungsartikel

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/tricks#91]
So eine Art Grundlagen-Artikel, wie [hier](https://kulturmanagement-online.de/blog/2017/02/05/texte-richtig-eingeben-was-beim-schreiben-in-wordpress-zu-beachten-ist/) für WP geschrieben, für die Benutzung von Redaxo. Für den DAU schreiben. 
Do/Dont/Was muss man beachten, wenn man nicht für Drucker oder PDF schreibt, sondern für ein CMS. Auch minimale Einführung in das Thema Strukturierung und Formatierung

Mir gefallen zB folgende Passagen:

> Immer wieder beobachte ich bei Kunden und Kollegen, dass sie Ihre Texte eingeben, als würden sie eine Schreibmaschine nutzen. Na gut, die meisten machen das in Office-Programmen genauso, aber deswegen ist es nicht unbedingt richtig. Meistens fehlt es an Grundlagen, Handlungsalternativen und einem Bewusstsein für die Auswirkungen. Ach ja und schnell gehen muss es ja auch immer …
> 
> Was nützt Dir das teure und aufwendig gestaltete Design, wenn Du danach Deine Seiten und Beiträge mit schlecht (unsauber) eingegebenem Text verunstaltest?
> 
> Ein paar Dinge, die ebenfalls zu einer eigentümlichen Gewohnheit bei vielen geworden sind, solltest Du unbedingt vermeiden. Streiche diese Handlungen am Besten ganz aus Deinem Repertoire.
> 
> Setze keine Leerzeilen.Ggf. ist der manuelle Zeilenumbruch eine Alternative.
> Versuche nicht Texte mit Leerzeichen zu positionieren.

**Comment by skerbis** [comment]
Als Ergänzung zu?: https://redaxo.org/doku/master/redaktion

**Comment by cukabeka** [comment]
Ja, genau, ist eher was für die Doku als für die Tricks. 👍

**Comment by skerbis** [comment]
@cukabeka magst du dich daran versuchen?

**Comment by skerbis** [comment]
Ich denke das ist eher was für die Tricks oder für einen Editor, da es in REDAXO verschiedene Editoren gibt, ist es schwer es allgemein zu formulieren.

**Comment by skerbis** [comment]
@cukabeka kommt hier noch was?

**Comment by skerbis** [comment]
ich close mal
