### ISSUE TITLE
Kategorien löschen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/tricks#92]
Seit dem die Tricks in diversen Kategorien abgelegt wurden, findet ich nur noch recht schwer was. Bin dann am zweifeln, ob ich es bei den docs oder sonst wo gesehen/erstellt/gelesen habe.

Das Arbeiten auf einer Ebene fand ich dagegen angenehmer.

**Comment by alexplusde** [comment]
![image](https://user-images.githubusercontent.com/3855487/43013422-2a563d78-8c49-11e8-9418-9ab84e99fbfd.png)

Hier kannst du alles aufklappen und suchen. Das wurde schon mehrfach diskutiert. (Ich fände es allerdings auch besser, direkt ein sichtbares Inhaltsverzeichnis ohne so viel white-space zu haben)

**Comment by skerbis** [comment]
Die Kategorien sind auch etwas unglücklich. Das Wording muss sicher mal geändert werden.

**Comment by schuer** [comment]
Ich finde die Kategorien strukturell gerade auch nicht allzu passend, denke aber, dass wir grundsätzlich Kategorien verwenden sollten, um nicht gleich die gesamte Navigation schon aufzuklappen. Das erschlägt einen (mich) zu sehr.

Mein Vorschlag wäre der von Skerbis: Wording und Struktur anpassen.

**Comment by schuer** [comment]
Hier weiter: #173
