### ISSUE TITLE
yForm objparams

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/tricks#93]
Immer wieder gesucht, wie zb einem Formular eine CSS Klasse mitgegeben werden kann. 

Im Yform editor können zb folgende Parameter übergeben werden:

```
objparams|form_skin|bootstrap
objparams|form_class|hide-label my-css-classname
```

**Comment by alexplusde** [comment]
Das ist nichts m.E. für tricks, sondern gehört in die YForm-Doku. Da sind viele Issues offen, was als Parameter noch möglich ist. Unterstützung ist da ebenfalls willkommen.

**Comment by skerbis** [comment]
Bitte an yForm übertragen und dort bearbeiten - close

**Comment by cukabeka** [comment]
Solange es in yform keine doku dazu gibt, bietet sich das doch vielleicht an, das in der addon-kategorie zu behandeln. Gerade, wo es so oft gefragt wird und nicht dokumentiert ist.

**Comment by skerbis** [comment]
muss es nicht form_ytemplate heißen anstelle von form_skin?

**Comment by tbaddade** [comment]
> muss es nicht form_ytemplate heißen anstelle von form_skin?

korrekt https://github.com/yakamara/redaxo_yform/commit/2cb7afea533b720fbc78abbc76594c03c4254d68#diff-6636be87aaa9803977529ef857327019

**Comment by skerbis** [comment]
kann man auch hier schön nachlesen :-) https://github.com/yakamara/redaxo_yform/blob/19e8f83da00f61a865181163d8ba4abffd9ca9c8/lib/yform.php#L22

**Comment by skerbis** [comment]
ist in der Doku beschrieben
