### ISSUE TITLE
Addons für Updates korrekt vorbereiten

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/tricks#94]
Stefan [Jul 16th at 8:36 AM]
Guten Morgen, kurze Frage. Beim Update über den Installer, ist es da wichtig alle bisher veröffentlichten Updates nacheinander (in chronologischer Reihenfolge) zu aktualisieren, oder kann man einfach direkt das Neuste aktualisieren und vorherige werden automatisch berücksichtigt?

7 replies
Dirk [9 days ago]
Moin. Brauchst nur das neuste.

Thomas [9 days ago]
Wichtig: auf die Hinweise auch der vorherigen Updates achten

Markus [9 days ago]
in der regel reicht das neuste. ist aber abhängig davon wie der update prozess des addons/plugins programmiert ist

Markus [9 days ago]
**wenn im addon die klassen benutzt werden, die der rex core mitrbingt  und dinge wie ensureColumn() ensureTable() etc genutzt werden, geht es**

Stefan [9 days ago]
OK, vielen Dank. Ich habe den Update nun durchgeführt, aber er war grade etwas hakelig. Das heisst, nach dem Update war der Status des Installers wie vor dem Update. Habt ihr einen kurzen Tip, wie ich auf einen Blick sehen kann, ob der Security Fix für den Media-Manager tatsächlich installiert ist? (Was ja erst mal das wichtigste ist)

Stefan [9 days ago]
Inzwischen sieht der Installer gut aus, nach Cache leeren und etwas abwarten.

Hirbod [9 days ago]
Es gibt auch nen Reload-Button im Installer. Normalerweise reicht es, diesen zu klicken

**Comment by skerbis** [comment]
Wo ist der Trick, bzw. das Problem?

**Comment by cukabeka** [comment]
Vielleicht ist das auch was fürs Demo-Addon, aber für Addon-Entwickler halte ich das für einen wichtigen Coding-Standard, der berücksichtigt werden sollte. @aeberhard ist da evtl noch ein guter Ansprechpartner

**Comment by skerbis** [comment]
Jupp alles hier: https://github.com/redaxo/docs/blob/master/datenbank-tabellen.md
Warum ist es nicht online @gharlan?

**Comment by alexplusde** [comment]
Ich glaube, das wäre in Addon-Entwicklung allgemein gut aufgehoben. best practices - z.B. kann man ja den Code für ensure() für eine Tabelle aus dem Adminer-Addon ablesen.

**Comment by skerbis** [comment]
> Coding-Standard,

@cukabeka,
 
@alexplusde es ist jetzt in der Doku
