### ISSUE TITLE
in metainfo-feld "date" das start- und endjahr festlegen

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/tricks#95]
weiß jemand, wie man metainfo-feld "date" das start- und endjahr festlegen kann? per default scheint das startdatum 13 jahren in der vergangenheit und das enddatum 10 in der zukunft zu liegen. ich muss jedoch weiter in die vergangenheit gehen.

Leider nein, aber du könntest auch ein Textfeld nehmen und den Typ auf Date ändern, falls die Lösung zulässig ist.

Peter [7 days ago]
wie meinst du? metainfo als textfeld anlegen. und dann wo auf date ändern?

Dirk [7 days ago]
im zweifel mit JS das vorausgewählte datum ändern. aber wenn es eine redaxo-lösung gibt, wäre die natürlich vorzuziehen. ich bin da nicht im thema.

Peter Bickel [7 days ago]
danke ... ich hoffe noch auf eine bessere lösung ... vielleicht morgen mal den @dergel fragen

Peter [7 days ago]
@dtpop ach jetzt weiß ich, was mit nachträglich auf date ändern gemeint ist, die yform-tools ... danke, das wäre eine notlösung!

Wolfgang [7 days ago]
Warum Notlösung? Funktioniert top. Man kann das Feld ja auch als Textfeld verwenden.

Wolfgang [7 days ago]
Mit dem Datepicker hat man dann auch noch mehr Eingabemöglichkeiten - zum Beispiel mit inputmask (find ich eh angenehmer zum eingeben als die doofen Picker). (edited)

Peter [7 days ago]
notlösung deshalb, weil man sich vielleicht die drei selectfelder vorgestellt hat und weil ich finde, dass es eine option geben sollte, hier start und ende selbst zu definieren. aber hast schon recht, der datenpicker hat schon auch seine vorteile

Alexander [7 days ago]
Genau, ich meinte ein Textfeld, dessen Type man ändert oder JS dranhängt.

Alexander [7 days ago]
Attribute: type=“date“ ... Und weitere HTML5-Attribute, um bspw. das Datum einzuschränken.

Peter [6 days ago]
ja, die kombination eurer vorschläge ist wirklich astrein, vielen dank euch allen! (und wolfgang hat recht, es ist keine "notlösung")

`$this->yearSelect->addOptions(range(2005, date('Y') + 10), true);`

**Comment by skerbis** [comment]
https://github.com/redaxo/redaxo/issues/2046

**Comment by skerbis** [comment]
redaxo/redaxo#2046 da sollte es weitergehen
