### ISSUE TITLE
yORM Beispiele

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/tricks#96]
Ein Anfrage zu Joins gab es hier:
https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1533039392000103

**Comment by skerbis** [comment]
Dieses Issue gehört aus meiner Sicht zur yForm Doku https://github.com/yakamara/redaxo_yform_docs

**Comment by cukabeka** [comment]
Hi, ich bin anderer Meinung. Nach meinem Verständnis sind gerade die Tricks für Sammelstelle für Fragen aus der Praxis von Usern in slack, und es gibt ja auch eine eigene Sektion für Addons. Natürlich wäre super, wenn das direkt in yform als Doku gepflegt wäre. Und aktuell sehe ich hier die Tricks als den besten Ort zum Sammeln von redaxo Wissen. Yorm verstehe ich sogar eher als übergreifend nützlich im redaxo Kontext. Und ich glaube, dass yorm gerade in den Tricks mehr Aufmerksamkeit verdient, da ich es als sehr mächtig und nützlich, aber weithin eher unbekannt einschätze.

**Comment by alexplusde** [comment]
Issue und Material gehört langfristig definitiv in die YForm-Doku, aber solange da keine klare Struktur dafür vorhanden ist und Updates nur spärlich stattfinden, sehe ich kein Problem, wenn in den Tricks was dazu veröffentlicht wird.

PR wellcome

**Comment by tbaddade** [comment]
Es gibt ja auch bereits Tricks zu Yorm. U.a.
https://github.com/FriendsOfREDAXO/tricks/blob/master/_docs/snippets/queries.md

**Comment by skerbis** [comment]
Bitte dann den in Slack hinterlegten Text hierhin ablegen. Nutzer ohne Slack-Zugang kommen da nicht dran. Bzw. ich nutze Slack nicht im Browser und kann es auch nicht aufrufen.

**Comment by cukabeka** [comment]
OK! :) 

Hier 2 YORM Threads:

```
Peter [Jun 28th at 5:40 PM]
Kann man mit YORM easy peasy die möglichen Values eines select-Felds abfragen (ist in der YForm Table angelegt)? Quasi auslesen der Struktur, ganz speziell des Felds "options".


6 replies
Gregor [1 month ago]
So mittel-easy


Gregor [1 month ago]
`rex_yform_manager_table::get(...)->getValueField(...)->getElement('options')`


Gregor [1 month ago]
irgendwie so


Peter [1 month ago]
Hatte es dann mit rex_sql gelöst. Ist jetzt auch nicht soooo viel länger der Code.


Gregor [1 month ago]
Aber die Abfrage oben nutzt einen Cache (edited)


Peter [1 month ago]
Ok, das ist n Argument...
```

und übrigens auch den hier:

> Thomas [Jul 24th at 1:28 PM]
> Moin. Hat jemand nen Tipp wie man in yOrm ein find_in_set macht?
> 
> 
> 7 replies
> Wolfgang [9 days ago]
> Das müsste mit whereRaw gehen.
> 
> 
> Thomas [9 days ago]
> habe es so lösen können:  ->where('rex_orte.cat', $values)->setWhereOperator('IN')
> 
> 
> Gregor [9 days ago]
> whereOperator muss `AND` oder `OR` sein, komisch, dass da bei dir kein fehler kommt
> 
> 
> Gregor [9 days ago]
> für `IN` braucht man nur das zu nutzen:
> `->where('rex_orte.cat', $values)`
> wenn $values ein Array ist, wird `IN` genutzt
> 
> 
> Gregor [9 days ago]
> Ach wahrscheinlich gibt es bei dir kein fehler, weil du nur eine where-bedingung hast, und somit der whereOperator gar nicht zum Tragen kommt
> 
> 
> Thomas [9 days ago]
> :slightly_smiling_face: ah
>

**Comment by skerbis** [comment]
ich glaube nicht, dass es irgendwem hilft in dieser Form.

**Comment by skerbis** [comment]
Ich verweise hier auf YForm Docs und bitte darum dort ein entsprechendes Issue zu erstellen.
https://github.com/yakamara/redaxo_yform_docs
