### ISSUE TITLE
yrewrite scheme

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/tricks#97]
Im yrewrite_scheme addon ist der Trick https://github.com/FriendsOfREDAXO/tricks/blob/master/addons_yrewrite_url_schemes.md verlinkt, aber zb hier https://github.com/FriendsOfREDAXO/tricks/tree/master/_docs/addons/yrewrite finde ich nichts mehr dazu. Wo ist der denn hingekommen?

**Comment by skerbis** [comment]
Danke für den Hinweis. Der Trickbeitrag ist bereits Teil der Dokumentation von yRewrite.
