### ISSUE TITLE
rex_list attribute

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/tricks#99]
### Q

Gibt es eine Möglichkeit, in einer rex_list Einfluss darauf zu nehmen, was genau in den *Attributen* des `<th>` und `<td>`-Tags steht? Also nicht der Inhalt...

### A

yes. funktioniert über die methode setColumnLayout

zu sehen z.b. hier https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/cronjob/pages/cronjobs.php#L67 
https://github.com/redaxo/redaxo/blob/master/redaxo/src/core/lib/list.php#L330-L339 (edited)

$list->setColumnLayout('name', ['<th>Test ###VALUE###</th>', '<td>Test ###VALUE###</td>']);

**Comment by alexplusde** [comment]
Gehört eher in die Doku, aber gut, dass es schon mal hier steht. Danke!

**Comment by skerbis** [comment]
Steht in der Doku sollte aber mal ‚ausgemalt‘ werden
